### ISSUE TITLE
Support for extended notifications in Win10 (like the Calendar app)

### ISSUE THREAD

**Issue by delold** [Windos/BurntToast#1]
Maybe something like this. 

![image](https://cloud.githubusercontent.com/assets/1443449/9025924/f3feca68-3919-11e5-9510-6384a60bfea6.png)

I do however think, that there isn't a new API for that yet, correct me if I'm wrong :smile:

**Comment by Windos** [comment]
Been developing on Win8 and only testing on Win10. Will see what can be done, thanks for the suggestion!

**Comment by Windos** [comment]
This is now supported (on Windows 10 at least)! The SnoozeAndDismiss switch parameter will show the standard system time options and buttons. A future version will allow for custom times and button text, and well as entirely custom actions.
