### ISSUE TITLE
BurntToast and .NET 5

### ISSUE THREAD

**Issue by SteveL-MSFT** [Windos/BurntToast#101]
In PowerShell 7.1 preview.4, .NET 5 removed built-in WinRT support.  Since BurntToast relies on this, this module will not work as-is with PowerShell 7.1.

See https://github.com/PowerShell/PowerShell/issues/13042#issuecomment-653357546 for a workaround.

**Comment by Windos** [comment]
Thanks @SteveL-MSFT, hoping to try out the workaround in the next day or two

**Comment by Windos** [comment]
v0.7.2 has shipped with the previews for those libraries in place for PowerShell 7.1. When those are GA'd they'll be included in further BT releases.

Thanks again @SteveL-MSFT!
