### ISSUE TITLE
Does not seem to work?

### ISSUE THREAD

**Issue by figueroadavid** [Windos/BurntToast#11]
Maybe I am doing something wrong.. but I've tried BT under PS x64, and PS x86, and even in basic mode, I run a simple test after importing the module (both PS versions):
`New-BurntToastNotification -Text 'Burnt Toast Test'`
And nothing seems to happen..  The help MD documents are fairly empty, so I'm kind of at a loss.

Just in case, here is my $PSVersionTable
```
Name                           Value
----                           -----
PSVersion                      5.1.14393.693
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.14393.693
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```
Poking around, I also saw that you could possibly add multiple lines, but the parameters don't seem to say that.. 

I appreciate any help :-) 

Thank you, 

David F.

**Comment by Windos** [comment]
Hi there David, thanks for the report! Yeah, sorry about the lack of MD documentation, it's very much a work in progress.

With regards to the multiple lines, the 'Text' parameter accepts an array, so you can provide multiple strings separated by a comma:

    New-BurntToastNotification -Text 'Burnt Toast Test', 'Second line of text'

Would you mind answering a few questions to help narrow the issue?

* Which version of BurntToast are you using?
* Which host are you using? ('Windows PowerShell'/CMD, the ISE, VS Code, PowerShell Studio)
* Is your PowerShell instance running as 'you'? (i.e. it wasn't started using 'Run as another user')

Look forward to hearing from you again, and seeing if we can sort this out!
~Josh

**Comment by figueroadavid** [comment]
Thank you for answering :-)
I just downloaded it.. it is the .5.1 versoin.
I was running it straight from PS 5.1 on Windows 10 (1607).  I tried both
the x64 PS and then I tried the x86 PS.

I did try it as myself, and as my Admin account.. (I am always logged in as
my normal user, but I also also have a CMD & PS shell session open as my
Domain Admin account for my "real" work).

If there is anything I can do to help on the documentation side, I'd be
glad to help.. I've been writing a lot of functions for things at work, and
to me, the docs and the command line help for PS are critical.  :-)

I will download it to my home machine and play with it more tonight.

Thank you!

David F.

**Comment by Windos** [comment]
Hey David, I just published a new version. Would you mind giving it another shot?

**Comment by figueroadavid** [comment]
I definitely will.. thank you! and I apologize for the delay... been a bit
busy :-)

I'll email again as soon as I try it out..

David F.

**Comment by figueroadavid** [comment]
No luck.. I don't think I'm doing anything wrong..

PS C:\Windows\system32\WindowsPowerShell\v1.0\Modules>
New-BurntToastNotification -Text "BurntToast Test"
PS C:\Windows\system32\WindowsPowerShell\v1.0\Modules>
New-BurntToastNotification -Text "Don't forget to smile!", 'Your
script ran successfully, celebrate!'
PS C:\Windows\system32\WindowsPowerShell\v1.0\Modules>
New-BurntToastNotification -Text 'WAKE UP!' -Sound 'Alarm2' -Snoo
zeAndDismiss
PS C:\Windows\system32\WindowsPowerShell\v1.0\Modules>
New-BurntToastNotification


None of them gave me a Toast message.. (Windows 10, Build 1607)

David F.

**Comment by Windos** [comment]
And you're getting no error messages?

Home, Pro, Enterprise or other edition of Win 10?

Are you using 'Run as different user' when starting PowerShell or running it through another host (like PowerShell Studio)?

**Comment by figueroadavid** [comment]
Windows 10, build 1607
Home version, elevated powershell prompt (I have PS Studio, but not using
it)

I will try this tomorrow on Win10 Creators Update, Enterprise version
tomorrow at work..

Thank you!

David F.

**Comment by figueroadavid** [comment]
I was able to make it work here @ work.. thank you!

One thing I did notice; is that the BT notification must be done in the context of the user running the Explorer shell.. I keep a PS prompt open with my Admin account, and when I ran a New-BurntToastNotification message from it, I got access denied, but I was able to use my regular account in both an elevated and non-elevated session to send BT notifications.

Thank you again for the awesome work.. I plan to definitely start incorporating this into many of my PS scripts!

David F.

**Comment by Windos** [comment]
I'm wondering if, for whatever reason this doesn't work on Home edition. I don't have my own license for that... but for this and another issue I'm tracking on another project I probably should.

Yeah, that user thing is a pain. An earlier version of this module used to check for that and warn if you were running the host as a different user than that which was interactively logged in. It also had a credential parameter so that if you triggered a toast from your admin host you could give the credentials of your standard user and it would display. I ended up removing this as it was jankily implemented and maintaining that was a pain.

If you find yourself needing to use it in that situation, you can always use `Invoke-Command` passing in your toast as the script block and specifying creds for you standard user.

**Comment by figueroadavid** [comment]
Well, thank you for the information..  I'm looking forward to being able to
use it.. and I'm sure you're right about the Home edition licensing thing,
but since I plan to use this on my work machine, and for my users, I'm good
with it :-)

If you are interested, you can download free/trial versions of the home
edition from Microsoft..   I'd have included a link, but MS is apparently
having trouble with their eval center.

Thank you again for an awesome module.. I can see a lot of great uses for
this..

David F.

**Comment by AmineI** [comment]
Sorry to bump this post - but I'm having the exact same issue ; and tried all the workaround you provided there, double checked that I was launching PowerShell as *me* , tried in the ISE, ISE x86, both as admin, same for the classic PowerShell, and I'm running out of ideas. Do you have any hint on what could be causing this behavior ?

Any of the example commands won't work either, no error message too, same symptoms as @figueroadavid 

--------
Note :  I do have Windows 10 Pro, and here's my $PSVersionTable

```
Name                           Value
----                           -----
PSVersion                      5.1.16278.1000
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.16278.1000
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

**Comment by Windos** [comment]
Hey @AmineI, no prob at all for bumping. I think the issue you're seeing is a slightly different one. Judging by your BuildVersion (10.0.16278.1000), I'm assuming you're on the Insider Previews?

It [looks like](https://github.com/Windos/BurntToast/issues/20) there's an issue with how I'm trying to get these Toast to show that the Fall Creator's Update doesn't like, as it's just blackholing them.

Hopefully we'll find a work around before that update goes GA!

**Comment by AmineI** [comment]
Indeed, I am ! I see, I'll go to the other issue thread then, I'll be glad to help !

**Comment by wisemoth** [comment]
Hello - I'm running Fall Creator's Edition, and have just excitedly installed this module.

I'm having the problem of seeing no toast, or errors,  either.  I've tried in admin and non-admin Powershell instances.

Here are my version tables.
```
PS C:\WINDOWS\system32> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      5.1.16299.98
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.16299.98
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1


PS C:\WINDOWS\system32> Get-Module BurntToast | select path,version

Path                                                                        Version
----                                                                        -------
C:\Program Files\WindowsPowerShell\Modules\BurntToast\0.6.1\BurntToast.psm1 0.6.1
```

Can I provide other diagnostics to help?

**Comment by Windos** [comment]
Hey @wisemoth, what command(s) are you running to get a Toast. Also, any warnings or errors if you explicitly import the module (`Import-Module BurntToast`)?

**Comment by figueroadavid** [comment]
Just so everyone knows, Joshua & I traded some emails about this thread, and my issue with BurntToast was the fact that I was trying on the Home version.  As soon as I tried it on Professional, it worked exactly as expected.

David f.

**Comment by wisemoth** [comment]
Thanks @figueroadavid , @Windos 

I'm running the Pro SKU:
```
PS C:\Users\owner> gwmi win32_operatingsystem|select -expand caption
Microsoft Windows 10 Pro
```

Here's verbose output from the module import - no errors or warnings.

```
PS C:\Users\owner> Import-Module BurntToast -Verbose
VERBOSE: Loading module from path 'C:\Program Files\WindowsPowerShell\Modules\BurntToast\0.6.1\BurntToast.psd1'.
VERBOSE: Importing function 'New-BTAction'.
VERBOSE: Importing function 'New-BTAppId'.
VERBOSE: Importing function 'New-BTAudio'.
VERBOSE: Importing function 'New-BTBinding'.
VERBOSE: Importing function 'New-BTButton'.
VERBOSE: Importing function 'New-BTContent'.
VERBOSE: Importing function 'New-BTContextMenuItem'.
VERBOSE: Importing function 'New-BTHeader'.
VERBOSE: Importing function 'New-BTImage'.
VERBOSE: Importing function 'New-BTInput'.
VERBOSE: Importing function 'New-BTProgressBar'.
VERBOSE: Importing function 'New-BTSelectionBoxItem'.
VERBOSE: Importing function 'New-BTText'.
VERBOSE: Importing function 'New-BTVisual'.
VERBOSE: Importing function 'New-BurntToastNotification'.
VERBOSE: Importing function 'Submit-BTNotification'.
VERBOSE: Importing alias 'Toast'.
PS C:\Users\owner>
```
I've tried several examples in `help NewBurntToastNotification` - no toast, nor alarm sound.

**Comment by BaconFist** [comment]
Hi, I've encountered a similar problem (but with win 10 pro).

But my notifications where simply disabled by default. You might check that.

**Comment by Windos** [comment]
I'm closing this issue for now, I've got other issues (and project notes) about individual topics that came up in this thread.

One is to confirm that this doesn't work on home (and then warn users trying to run the module against the home edition)

The second is to do more to check for the updates being disabled.

I'm currently targeting both of these being sorted in v0.7.1 (which will not be next release, but the release after that.)

**Comment by mkanet** [comment]
Just a tip... Also, check to make sure you didn't accidentally set Windows Focus Assistant to "Priority Only" or "Alarms Only" under Windows Action Center when you click on the Notifications area.
