### ISSUE TITLE
Installed, but no commands available

### ISSUE THREAD

**Issue by ArchbishopFlabrus** [Windos/BurntToast#12]
After installing the module, I cannot use it.  

I get the following message:

```
PS C:\WINDOWS\system32> New-burntoastnotification
New-burntoastnotification : The term 'New-burntoastnotification' is not recognized as the name of a cmdlet, function,
script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is
correct and try again.
At line:1 char:1
+ New-burntoastnotification
+ ~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (New-burntoastnotification:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
```

I confirmed that the module is actually installed, and accessible, but it lists no ExportedCommands (*Output truncated for brevity.*):

```
PS C:\WINDOWS\system32> Get-Module -ListAvailable


    Directory: C:\Program Files\WindowsPowerShell\Modules


ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Script     0.5.1      BurntToast

```

I checked that I'm running Powershell v5.1...

```
PS C:\WINDOWS\system32> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      5.1.14393.693
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.14393.693
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

Am I missing a step here?  What am I doing wrong?

**Comment by KosherSalt** [comment]
Try running `Import-Module BurntToast`
I confirmed that I see the same thing as you if the module isn't imported in. PowerShell modules aren't automatically imported from the modules folder. I'd recommend putting the import in your profile or the top of the script you're writing.

**Comment by Windos** [comment]
Thanks for the report. It looks like there's an issue with the module at the moment because I've tried to separate cmdlets into 'Basic' and 'Advanced'.

Hoping this will be sorted in the next release, in the short term importing the module will get it going.

**Comment by ArchbishopFlabrus** [comment]
Thanks for the tip.  Much obliged.

Thanks for all your work!
