### ISSUE TITLE
Example 08 - simple HTTP listener errors out with "Invalid Hostname" on port 9000

### ISSUE THREAD

**Issue by DaneManes** [Windos/BurntToast#121]
## Steps to reproduce

Start Powershell IDE as admin on target system - start Example 08 listener code using port 9000

Start Powershell IDE ad admin on source system - start Example 08 sender code using port 9000

## Expected behavior
Should initiate a BT popup as indicated in the example

## Actual behavior
On the source system, sender gets following error message:
> Invoke-RestMethod -Method Post -Body ($Body | ConvertTo-Json) -Uri "http://hudibu-pc:9000/"
> Invoke-RestMethod : 
> Bad Request
> Bad Request - Invalid Hostname
> HTTP Error 400. The request hostname is invalid.

If I change the target port to 9001 instead I get this (correct) error message:
> Invoke-RestMethod -Method Post -Body ($Body | ConvertTo-Json) -Uri "http://hudibu-pc:9001/"
> Invoke-RestMethod : The connection to the remote server cannot be established

Sry for ad-lib but source system is running German

## Environment data
> Name                           Value                                                                                                 
> ----                           -----                                                                                                 
> PSVersion                      5.1.19041.1                                                                                           
> PSEdition                      Desktop                                                                                               
> PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                               
> BuildVersion                   10.0.19041.1                                                                                          
> CLRVersion                     4.0.30319.42000                                                                                       
> WSManStackVersion              3.0                                                                                                   
> PSRemotingProtocolVersion      2.3                                                                                                   
> SerializationVersion           1.1.0.1    

I'm at my wits end as I've disabled firewalls, etc but it seems to choke on the indicated port - if I increment or decrement the port for the target machine, or use any other PC on my network which is *not* running powershell and BT it errors out properly with a "no connection" message - but on the target system the error is a dubious "invalid hostname" which caused a few hours of DNS soul-searching before I thought to try an unrelated port.

**Comment by Windos** [comment]
Looks like this is a quirk in either `Invoke-RestMethod` or the underlying .NET stuff.

The example as written does work. The listener is configured to listen to "localhost:9000", so if you run `Invoke-RestMethod -Method Post -Body ($Body | ConvertTo-Json) -Uri "http://localhost:9000/"` you will get a notification.

As soon as you try to call that listener locally using anything other than localhost, it seems like the HttpListener doesn't know how to handle it. I'm not actually sure if this setup work **at all** over the network?

It should be noted that these examples are community provided and meant as "huh, that's cool" type snippets intended to spark ideas of how this module could be used with some more fleshing out.

If this is a use case you're wanting to pursue, I'd highly recommend looking into something that's more production ready as an "API endpoint" than having a constant HttpListener running (Maybe [PowerShell Universal](https://ironmansoftware.com/powershell-universal/) or [Polaris](https://github.com/PowerShell/Polaris), though that one is unsupported.)

**Comment by DaneManes** [comment]
Many thanks - the issue was a missing http config in Windows 10 allowing external traffic.

The call is similar to
```
netsh http>add urlacl url=http://+:9000/toast/ user=BUILTIN\Users listen=yes
URL reservation successfully added
```
where the url entered in netsh must exactly match that of the registered listener in powershell.  Thanks to https://www.msxfaq.de/code/powershell/pshttpserver.htm for the hints on what to change (page is in German).
