### ISSUE TITLE
Header ID shouldn't be mandatory!

### ISSUE THREAD

**Issue by Windos** [Windos/BurntToast#125]
## Summary of the new feature/enhancement

[`New-BTHeading`](https://github.com/Windos/BurntToast/blob/main/BurntToast/Public/New-BTHeader.ps1) requires an ID as this is required in the Windows APIs. It is how Windows knows to group multiple notifications under the same heading.

This feels a little cumbersome for most use cases, surely it could be dynamic?

## Proposed technical implementation details (optional)

Perhaps if an ID isn't specified, the function should automatically re-use the title...

**Comment by glennsarti** [comment]
@Windos   May I have a go at this?

**Comment by Windos** [comment]
@glennsarti go for it!

**Comment by steviecoaster** [comment]
Dang it Glenn, beatin me too things :joy:

**Comment by Windos** [comment]
And Glenn nailed it 😄
