### ISSUE TITLE
[Feature Request Summary] Support for mobile notifications using notify17?

### ISSUE THREAD

**Issue by vmiheer** [Windos/BurntToast#135]
## Send mobile notifications using [notify17](https://notify17.net/)

Burnt-Toast is great but it would be better if it could also send IOS notifications using notify17.

## Burntoast notify17 flow

1. For `New-BurntToastNotification` applet there would be additional argument: `-ExternNotify` option.
   `-ExternNotify` option would take `notify17` as argument initially, but it could be extended to adding `email` or other notification options.
2. First use, any `-ExternNotify` plugin will check for saved credentials in a file (let's say: ~/.burntoastconfig`), if it couldn't find any section in that file, it will ask any authentication data needed. In case of notify17, it will just be api key.
    It will save the authentication data as [Secure-String](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.security/convertto-securestring?view=powershell-7) and dump in file for later use.
3. For all later uses, it will just convert secure string to plain text and the plugin will handle the rest.

**Comment by Windos** [comment]
This module focuses exclusively on the full feature set available for toasts via the Windows API.

You're welcome to borrow whatever code is needed from this module to create one for Notify17, and in that case I'd also encourage adding it to the roster for [PoshNotify](https://www.powershellgallery.com/packages/PoshNotify) (which combines the common features for [Linux](https://www.powershellgallery.com/packages/PSNotifySend), [Mac](https://www.powershellgallery.com/packages/MacNotify), and [Windows](https://www.powershellgallery.com/packages/BurntToast))
