### ISSUE TITLE
On click action

### ISSUE THREAD

**Issue by iTob191** [Windos/BurntToast#15]
Is there a way to define an action that is executed when you click on the notification? Like opening a program or web page.
I know that you can add a button with such functionality, but can you do the same with the notification directly?

**Comment by Windos** [comment]
There is! I (finally) realised this while working on v0.6.0 but didn't have a chance to document it before release.

Unfortunately at the moment it's not possible to do this using only the `New-BurntToastNotification` function, so you need to dive into the more advanced functions:

    $Text1 = New-BTText -Content 'Google!'
    $Text2 = New-BTText -Content 'Clicking this will open Google.'

    $Binding1 = New-BTBinding -Children $Text1, $Text2

    $Visual1 = New-BTVisual -BindingGeneric $Binding1

    $Content1 = New-BTContent -Visual $Visual1 -Launch 'https://google.com' -ActivationType Protocol

    Submit-BTNotification -Content $Content1

The key to this is on the `New-NTContent` function: defining the `-Launch` as the url/uri/path you want to open, and setting the `-ActivationType` to Protocol.

Note that if you have buttons or progress bars or anything else on there, the clickable area is only the pictures/main text (clicking to progress bar is a deadzone, from memory)

I'll hopefully figure out a way to make this easier in the next release.

**Comment by ImmortalPC** [comment]
There is a lite bypass with small dll.
See: https://deletethis.net/dave/2016-06/WinRT+Toast+from+PowerShell

**Comment by Windos** [comment]
Thanks for that link, very helpful. I'd considered bundling a compiled exe to handle this early on in the project and decided against it at the time.

I wonder if, like you say, it'd be possible to get this working in native PowerShell. We're working with PS5 here... so possibly PowerShell classes could be used.

As an aside, this issue prompted a [blog post](http://king.geek.nz/2017/05/08/crouton-clickable/) if anyone is interested.

**Comment by ImmortalPC** [comment]
An other way could be to create a new handler for a internal protocol.
`$Content1 = New-BTContent -Visual $Visual1 -Launch 'BurntToast://my-data' -ActivationType Protocol`
But this tricks dosen't work with complex toast:

```
<toast duration="5">
    <visual>
        <binding template="ToastGeneric">
            <text>This is a test</text>
            <text />
            <text>This more testing</text>
            <text>RAWR</text>
            <image src="C:\Users\King\Documents\GitHub\BurntToast\Media\BurntToast.png" hint-removeMargin="false" />
        </binding>
    </visual>
    <audio src="ms-winsoundevent:Notification.SMS" />
    <actions>
        <input id="snoozeTime" type="selection" defaultInput="3">
            <selection id="1" content="1 Minutes" />
            <selection id="2" content="2 Minutes" />
            <selection id="3" content="3 Minutes" />
            <selection id="4" content="4 Minutes" />
            <selection id="5" content="5 Minutes" />
        </input>
        <action content="" arguments="snooze" activationType="system" />
        <action content="" arguments="dismiss" activationType="system" />
    </actions>
</toast>
```

**Comment by dzfweb** [comment]
is there a way to call some function instead of launch browser?

In my case i want to focus a proccess by id. 

`Set-ForegroundWindow (Get-Process -id $procid).MainWindowHandle`

**Comment by Windos** [comment]
I'll do some testing tonight, but thinking through it now: not directly because the string that's included as the action on a button isn't running inside PowerShell.

However, in theory anything you can do from the 'Run' dialogue should work where, so you might be able to start a PowerShell.exe instance with the function you want to run as an argument.

**Comment by AmineI** [comment]
> However, in theory anything you can do from the 'Run' dialogue should work where, so you might be able to start a PowerShell.exe instance with the function you want to run as an argument.

May I ask how would you launch an exe from a toast ? From my testing I could only launch files other than executables with that -launch:"" argument. Launching a .txt file opens the file in notepad, yet the exact path of notepad.exe didn't do the trick - Am I missing something there ?
Thanks in advance for your answer :)

**Comment by Windos** [comment]
I know this is an old issue, but it deserves a wrap up with links to relevant info.

First, Custom URIs/Protocol Handlers: @adamdriscoll does an awesome job of showing this in this [Module Monday](https://youtu.be/TwZjr66yfc8) video on BurntToast. I've also demo'ed it for the Research Triangle PowerShell User Group, the sample code for that is on [their repo](https://github.com/rtpsug/Meetups/tree/master/2020/06-June/Community%20Code%20Sharing/Josh%20King%20-%20Toast%20Magic).

Second, ACTIONABLE TOASTS!

It's now possible to run any code via a toast notification action. This does require PowerShell 7.1 or above and BurntToast 0.8.0.

This [blog post](https://toastit.dev/2020/08/08/actionable/) shows it in action, though with v0.8.0 it's a lot easier to take advantage of this via some new parameters on New-BurntToastNotification and Submit-BTNotification. Documentation for this is  coming soon, for now check out the end of this [live stream](https://youtu.be/8TuqVs7QGz0).
