### ISSUE TITLE
BurntToast was working then stopped

### ISSUE THREAD

**Issue by RockFox** [Windos/BurntToast#16]
I was successfully running version 0.5.2 in Windows 10 Pro and then decided to upgrade to version 0.6.0.  I opened a PowerShell session and I was issuing various BurntToast commands with success and for some reason I started getting errors on every attempt.  I tried re-installing 0.5.2 and it wouldn't work with same error messages.  I then did a System Restore to a point before installing 0.6.0.  I removed BurntToast folder from C:\Users\Fran\Documents\WindowsPowerShell\Modules and then manually installed 0.6.1.  Still no joy!  Below is output from trying   New-BurntToastNotification

PS C:\users\fran\documents\WindowsPowerShell\modules\burnttoast\lib> dir
    Directory: C:\users\fran\documents\WindowsPowerShell\modules\burnttoast\lib
Mode                LastWriteTime         Length Name
----                -------------         ------ ----
d-----        6/23/2017  12:45 PM                Microsoft.Toolkit.Uwp.Notifications

PS C:\users\fran\documents\WindowsPowerShell\modules\burnttoast\lib> cd ..
PS C:\users\fran\documents\WindowsPowerShell\modules\burnttoast> New-BurntToastNotification
Unable to find type [Microsoft.Toolkit.Uwp.Notifications.IToastButton].
At C:\Users\Fran\Documents\WindowsPowerShell\Modules\BurntToast\Public\New-BurntToastNotification.ps1:149 char:9
+         [Microsoft.Toolkit.Uwp.Notifications.IToastButton[]] $Button,
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (Microsoft.Toolk...ns.IToastButton:TypeName) [], RuntimeException
    + FullyQualifiedErrorId : TypeNotFound

PS C:\users\fran\documents\WindowsPowerShell\modules\burnttoast>
PS C:\users\fran\documents\WindowsPowerShell\modules\burnttoast> cd lib
PS C:\users\fran\documents\WindowsPowerShell\modules\burnttoast\lib> dir

    Directory: C:\users\fran\documents\WindowsPowerShell\modules\burnttoast\lib

Mode                LastWriteTime         Length Name
----                -------------         ------ ----
d-----        6/23/2017  12:45 PM                Microsoft.Toolkit.Uwp.Notifications

PS C:\users\fran\documents\WindowsPowerShell\modules\burnttoast\lib> cd Microsoft.Toolkit.Uwp.Notifications
PS C:\users\fran\documents\WindowsPowerShell\modules\burnttoast\lib\Microsoft.Toolkit.Uwp.Notifications> dir

    Directory: C:\users\fran\documents\WindowsPowerShell\modules\burnttoast\lib\Microsoft.Toolkit.Uwp.Notifications

Mode                LastWriteTime         Length Name
----                -------------         ------ ----
-a----        6/23/2017  12:45 PM          90456 Microsoft.Toolkit.Uwp.Notifications.dll
-a----        6/23/2017  12:45 PM         284160 Microsoft.Toolkit.Uwp.Notifications.pdb
-a----        6/23/2017  12:45 PM         113822 Microsoft.Toolkit.Uwp.Notifications.xml

PS C:\users\fran\documents\WindowsPowerShell\modules\burnttoast\lib\Microsoft.Toolkit.Uwp.Notifications>

**Comment by RockFox** [comment]
Update:  BurntToast is working finewhen invoked by an [ooRexx ](http://www.oorexx.org/)program:

AppLogo = 'C:\Users\Fran\Documents\WindowsPowerShell\Modules\BurntToast\Images\MinistryScheduler.png'
BurntToast = "PowerShell New-BurntToastNotification"
BurntToastDebug = 'PowerShell Set-PSDebug -Trace 1; New-BurntToastNotification'
-- One string of white text on the first line, one string of regular text second, no image.
BurntToastDebug "-text 'Ministry Scheduler', 'Don''t forget to check for conflicts' -applogo" AppLogo

**Comment by RockFox** [comment]
Same program as I reported working on Jun 25: (Windows 10 Pro Version 1703, BurntToast 0.6.1)

DEBUG:    1+ Set-PSDebug -Trace 1;  >>>> New-BurntToastNotification -text 'Ministry Scheduler', 'Don''t forget to check
 for conflicts' -applogo C:\Users\Fran\Documents\WindowsPowerShell\Modules\BurntToast\Images\MinistrySchedulerPro.ico

Security warning
Run only scripts that you trust. While scripts from the internet can be useful, this script can potentially harm your
computer. If you trust this script, use the Unblock-File cmdlet to allow the script to run without this warning
message. Do you want to run C:\Users\Fran\Documents\WindowsPowerShell\Modules\BurntToast\BurntToast.psm1?
[D] Do not run  [R] Run once  [S] Suspend  [?] Help (default is "D"): R
DEBUG:   19+                                         if ( &  >>>> { Set-StrictMode -Version 1; $_.PSMessageDetails } )
{
DEBUG:   19+                                         if ( & {  >>>> Set-StrictMode -Version 1; $_.PSMessageDetails } )
{
DEBUG:   19+                                         if ( & { Set-StrictMode -Version 1;  >>>> $_.PSMessageDetails } )
{
DEBUG:    1+ &  >>>> { Set-StrictMode -Version 1; $this.Exception.InnerException.PSMessageDetails }
DEBUG:    1+ & {  >>>> Set-StrictMode -Version 1; $this.Exception.InnerException.PSMessageDetails }
DEBUG:    1+ & { Set-StrictMode -Version 1;  >>>> $this.Exception.InnerException.PSMessageDetails }
DEBUG:    1+ & { Set-StrictMode -Version 1; $this.Exception.InnerException.PSMessageDetails  >>>> }
DEBUG:   19+                                         if ( & { Set-StrictMode -Version 1; $_.PSMessageDetails  >>>> } )
{
DEBUG:   26+                                         $errorCategoryMsg = &  >>>> { Set-StrictMode -Version 1;
$_.ErrorCategory_Message }
DEBUG:   26+                                         $errorCategoryMsg = & {  >>>> Set-StrictMode -Version 1;
$_.ErrorCategory_Message }
DEBUG:   26+                                         $errorCategoryMsg = & { Set-StrictMode -Version 1;  >>>>
$_.ErrorCategory_Message }
DEBUG:   26+                                         $errorCategoryMsg = & { Set-StrictMode -Version 1;
$_.ErrorCategory_Message  >>>> }
DEBUG:   42+                                         $originInfo = &  >>>> { Set-StrictMode -Version 1; $_.OriginInfo
}
DEBUG:   42+                                         $originInfo = & {  >>>> Set-StrictMode -Version 1; $_.OriginInfo
}
DEBUG:   42+                                         $originInfo = & { Set-StrictMode -Version 1;  >>>> $_.OriginInfo
}
DEBUG:   42+                                         $originInfo = & { Set-StrictMode -Version 1; $_.OriginInfo  >>>>
}
Unable to find type [Microsoft.Toolkit.Uwp.Notifications.IToastButton].
At C:\Users\Fran\Documents\WindowsPowerShell\Modules\BurntToast\Public\New-BurntToastNotification.ps1:149 char:9
+         [Microsoft.Toolkit.Uwp.Notifications.IToastButton[]] $Button,
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (Microsoft.Toolk...ns.IToastButton:TypeName) [], RuntimeException
    + FullyQualifiedErrorId : TypeNotFound

**Comment by RockFox** [comment]
Update:  On a Windows 10 Pro Version 1607 that never had BurntToast installed I invoked Command Prompt (Admin) then PowerShell and did a PowerShell Gallery Install of BurntToast.  All went well.  Here is a transcript of the whole session:

Microsoft Windows [Version 10.0.14393]
(c) 2016 Microsoft Corporation. All rights reserved.

C:\WINDOWS\system32>powershell
Windows PowerShell
Copyright (C) 2016 Microsoft Corporation. All rights reserved.

PS C:\WINDOWS\system32> Install-Module -Name BurntToast

NuGet provider is required to continue
PowerShellGet requires NuGet provider version '2.8.5.201' or newer to interact with NuGet-based repositories. The NuGet
 provider must be available in 'C:\Program Files\PackageManagement\ProviderAssemblies' or
'C:\Users\Fran\AppData\Local\PackageManagement\ProviderAssemblies'. You can also install the NuGet provider by running
'Install-PackageProvider -Name NuGet -MinimumVersion 2.8.5.201 -Force'. Do you want PowerShellGet to install and import
 the NuGet provider now?
[Y] Yes  [N] No  [S] Suspend  [?] Help (default is "Y"): Y

Untrusted repository
You are installing the modules from an untrusted repository. If you trust this repository, change its
InstallationPolicy value by running the Set-PSRepository cmdlet. Are you sure you want to install the modules from
'PSGallery'?
[Y] Yes  [A] Yes to All  [N] No  [L] No to All  [S] Suspend  [?] Help (default is "N"): A
PS C:\WINDOWS\system32> New-BurntToastNotification
New-BurntToastNotification : The 'New-BurntToastNotification' command was found in the module 'BurntToast', but the
module could not be loaded. For more information, run 'Import-Module BurntToast'.
At line:1 char:1
+ New-BurntToastNotification
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (New-BurntToastNotification:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CouldNotAutoloadMatchingModule

PS C:\WINDOWS\system32> Import-Module BurntToast
Import-Module : File C:\Program Files\WindowsPowerShell\Modules\BurntToast\0.6.0\BurntToast.psm1 cannot be loaded
because running scripts is disabled on this system. For more information, see about_Execution_Policies at
http://go.microsoft.com/fwlink/?LinkID=135170.
At line:1 char:1
+ Import-Module BurntToast
+ ~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : SecurityError: (:) [Import-Module], PSSecurityException
    + FullyQualifiedErrorId : UnauthorizedAccess,Microsoft.PowerShell.Commands.ImportModuleCommand
PS C:\WINDOWS\system32> set-executionpolicy remotesigned
PS C:\WINDOWS\system32> Import-Module BurntToast
PS C:\WINDOWS\system32> New-BurntToastNotification
WARNING: The AppId BurntToast is not present in the registry, please run New-BTAppId to avoid inconsistent Toast
behaviour.
PS C:\WINDOWS\system32> New-BTAppID BurnetToast
PS C:\WINDOWS\system32> New-BurntToastNotification
WARNING: The AppId BurntToast is not present in the registry, please run New-BTAppId to avoid inconsistent Toast
behaviour.
PS C:\WINDOWS\system32> New-BTAppID BurntToast
PS C:\WINDOWS\system32> New-BurntToastNotification
PS C:\WINDOWS\system32> New-BurntToastNotification -Text "Don't forget to smile!", 'Your script ran successfully, celebrate!' -AppLogo C:\smile.jpg
>>
PS C:\WINDOWS\system32> New-BurntToastNotification -Text 'WAKE UP!' -Sound 'Alarm2' -SnoozeAndDismiss
PS C:\WINDOWS\system32>

**Comment by RockFox** [comment]
Resolved:  I think I have found the reason for my problems with BurntToast.

The PowerShell Gallery Install put BurntToast in
C:\Program Files\WindowsPowerShell\Modules

The manual install instructions say to unzip and copy to:
C:\Users\[user]\Documents\WindowsPowerShell\Modules

In trying to resolve my problems I think I used BOTH install procedures. 

 I deleted the 
C:\Users\[user]\Documents\WindowsPowerShell
And then used the PowerShell Gallery Install.  I did a few tests and BurntToast seems to be working well.

Note that the Smile example has   -AppLogo C:\smile.jpg
This .jpg does not exist in Images folder.

**Comment by Windos** [comment]
I wonder if the manual install was suffering from the same issue as #21, where the DLLs were being blocked  by Windows?

My understanding is that if the module is downloaded via the gallery then they aren't blocked.

If you *do* want the module to be located in your user profile when installing from the gallery you can do so with the Scope parameter:

    Install-Module -Name BurntToast -Scope CurrentUser

**Comment by Windos** [comment]
I've added a note about unblocking the zip file to the README, in case that was the issue here. Preference should be to download from the Gallery (which avoids the blocking issue).
