### ISSUE TITLE
Is it possible to use images from the web?

### ISSUE THREAD

**Issue by WindfallProphet** [Windos/BurntToast#18]
Like the samples in [Notification Visualizer](https://docs.microsoft.com/en-us/windows/uwp/controls-and-patterns/tiles-and-notifications-notifications-visualizer) ([Webstore](https://www.microsoft.com/en-us/store/p/notifications-visualizer/9nblggh5xsl1?rtc=1))

**Comment by Windos** [comment]
It *should* be possible, and I'm not sure why it's not just working.

I'll do some digging and aim to have this working in the next release.

**Comment by Windos** [comment]
Hey @WindfallProphet, pushed v0.6.2 to the gallery this morning.

Ended up having to make it so that the image parts of the module will download the image to `$env:TEMP`  and use them from there.

Means you can now use images from the web!
