### ISSUE TITLE
Notifications intermittently return even after having been cleared

### ISSUE THREAD

**Issue by Artfunkel** [Windos/BurntToast#2]
I've been using BurntToast for some time and I've noticed that sometimes when I check the Action Centre I'll see all notifications the module has created since I turned my computer on, even though I've previously cleared the list. They must be hanging around somewhere.

I've not worked out precisely what triggers this behaviour, and I've not seen this issue with any other program which creates notifications.

**Comment by Windos** [comment]
Good catch, I haven't noticed this myself yet. What OS are you on (if Win10, what build)?

**Comment by Artfunkel** [comment]
Windows 10 x64 version 1511 (10586.63).

**Comment by Windos** [comment]
@Artfunkel, not sure if you're still using this module. It looks like newer updates of Windows seem to be handling these notification better now, though I'm still working on properly supporting AppIDs which play into this. The next release should resolve your issue (if it isn't already.)

**Comment by Artfunkel** [comment]
I'm not, but I appreciate the effort. 😊
On 10 Nov 2016 00:40, Joshua King <notifications@github.com> wrote:@Artfunkel, not sure if you're still using this module. It looks like newer updates of Windows seem to be handling these notification better now, though I'm still working on properly supporting AppIDs which play into this. The next release should resolve your issue (if it isn't already.)

**Comment by lypanov** [comment]
I'm seeing this same issue even with a correctly set up AppId. I'll try a reboot to see if you need a reboot after having created some without the AppId.

**Comment by lypanov** [comment]
Ignore my last message. PEBCAK.

**Comment by Windos** [comment]
Hey @lypanov, sorry I missed your initial comment. Was the issue something that could be prevented in the future if I do something to help (more validation in the module or better documentation)?

**Comment by lypanov** [comment]
Hey thanks @Windos no couldn't be helped - my Windows install decided to switch randomly to US style dates and I missed the change happening a while back.

I love BurntToast just so you know :) I use it to notify me when some long jobs finish in my work environment (WSL / Ubuntu / Ruby). And another to let me know when my File History backup has completed (so I can unplug the drive). Amazing how diverse the use cases can be! :D
