### ISSUE TITLE
Notifications don't display in Windows Fall Creator's Update

### ISSUE THREAD

**Issue by scowalt** [Windos/BurntToast#20]
### Repro steps

1. Install an [Insider build](https://insider.windows.com) for the Fall Creator's Update (currently available in the Slow or Fast rings)
2. Install the BurntToast Module (repros on version `0.6.0`, haven't tried the development version)
3. Attempt to send any notification (i.e. `New-BurntToastNotification`)

I'm not sure if this is due to an OS bug or just an API change. Wanted to make this issue known before the update is released later this year.

Cheers!

**Comment by Windos** [comment]
Thanks for the report! I've been off of the insider builds for a while,
will test. Do you have an AppId set, and if not is it throwing a warning in
the console?

**Comment by scowalt** [comment]
I don't have an AppId set, and there is no error in the console:
![image](https://user-images.githubusercontent.com/1100550/28896662-36355e52-7792-11e7-80a7-528d1f96d6a6.png)

Setting an AppId removes the warning, but there is still no console error and no notification:
![image](https://user-images.githubusercontent.com/1100550/28896696-55b46a0c-7792-11e7-9020-f8346820da81.png)

**Comment by Windos** [comment]
I've been able to reproduce, and confirmed that latest version of the UWP Community Toolkit doesn't fix the issue. Will work to figure it out.

Thanks again for reporting this!

**Comment by AmineI** [comment]
There was a new version of UWP Toolkit https://www.nuget.org/packages/Microsoft.Toolkit.Uwp.Notifications/ as of 11 days ago, maybe that one could help ? Just a suggestion though

**Comment by jholl016** [comment]
Any update on compatibility for Windows 10 1709 (Fall Creator's Update)?

**Comment by scowalt** [comment]
It looks like this was fixed by #23. Thanks for addressing this issue!
