### ISSUE TITLE
"Operation is not supported" on Module load

### ISSUE THREAD

**Issue by ElvenSpellmaker** [Windos/BurntToast#21]
Problem:
```
PS path> Import-Module -Name .\BurntToast
pathtomodule\BurntToast\BurntToast.psm1 : Failed to load library pathtomodule\BurntToast\lib\Microsoft.Toolkit.Uwp.Notifications\Microsoft.Toolkit.Uwp.Notifications.dll: Could not load file or assembly 'file:///pathtomodule\BurntToast\lib\Microsoft.Toolkit.Uwp.Notifications\Microsoft.Toolkit.Uwp.Notifications.dll' or one of its dependencies. Operation is not supported. (Exception from HRESULT: 0x80131515)
At line:1 char:1
+ Import-Module -Name .\BurntToast
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,BurntToast.psm1`
```

Cause:
When downloading DLLs Microsoft puts a block on them for safety reasons.

Solution:
Unblock the DLL in explorer:
![image](https://user-images.githubusercontent.com/2286713/29241344-638ae4d2-7f6f-11e7-8ef6-7cb697c68a5e.png)

Alternatively unblock it using the powershell command `Unblock-File`: https://docs.microsoft.com/en-us/powershell/module/Microsoft.PowerShell.Utility/Unblock-File?view=powershell-5.1

Suggestion:
Maybe adding this to the readme, or adding a note somewhere explaining that this might be needed to be done to fix the loading problem.

**Comment by Windos** [comment]
Thanks for the report/suggestion. I think this was in a very early version of the readme, but I dropped it at some stage. Will add it back in.

**Comment by Windos** [comment]
I've added a note about unblocking the zip file to the README. I'm not including a download script as I'd much prefer people to download from the Gallery (which avoids the blocking issue).
