### ISSUE TITLE
[Bug]: Update-BTNotification not doing its job even when verbose shows no error.

### ISSUE THREAD

**Issue by Silloky** [Windos/BurntToast#213]
### Steps to Reproduce

```powershell
$binding = @{
    text1 = "Downloading your files..."
    text2 = "Your files are being downloaded so they can be available offline."
    value = 0
    status = "Downloading..."
}
$progress = New-BTProgressBar -Status $binding['status'] -Value $binding['value']
New-BurntToastNotification -Text $binding['text1'], $binding['text2'] -AppLogo $binding['image'] -ProgressBar $progress -UniqueIdentifier "toast"
foreach ($n in 1..100){
    $binding['value'] = $binding['value'] + 0.01
    Update-BTNotification -UniqueIdentifier "toast" -DataBinding $binding
    Start-Sleep 1
}
```

### Expected Behavior

The toast should be replaced every second by a higher percentage and a different progress bar.

### Actual Behavior

It doesn't do that and the toast disappears after 5 seconds or so.

### Experience with Toast

Beginner

### Environment data: PowerShell

```text
Name                           Value
----                           -----
PSVersion                      5.1.22621.608
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.22621.608
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

### Environment data: OS

```text
OsName         : Microsoft Windows 11 Pro
OsVersion      : 10.0.22621
OsArchitecture : 64-bit
```

### Environment data: BurntToast

```text
Directory: C:\Program Files\WindowsPowerShell\Modules


ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Script     0.8.5      BurntToast                          {Get-BTHistory, New-BTAction, New-BTAppId, New-BTAudio...}
```

### Consent to Attribution

- [X] Please shout me out if I've inspired a blog post!

**Comment by xianrui69** [comment]
$binding = @{
    text1 = "Downloading your files..."
    text2 = "Your files are being downloaded so they can be available offline."
    value = 0
    status = "Downloading..."
}
$progress = New-BTProgressBar -Status 'status' -Value 'value'
New-BurntToastNotification -Text $binding['text1'], $binding['text2'] -AppLogo $binding['image'] -ProgressBar $progress -UniqueIdentifier "toast" -DataBinding $binding
foreach ($n in 1..100){
    $binding['value'] = $binding['value'] + 0.01
    Update-BTNotification -UniqueIdentifier "toast" -DataBinding $binding
    Start-Sleep 1
}

**Comment by xianrui69** [comment]
> $binding = @{ text1 = "Downloading your files..." text2 = "Your files are being downloaded so they can be available offline." value = 0 status = "Downloading..." } $progress = New-BTProgressBar -Status 'status' -Value 'value' New-BurntToastNotification -Text $binding['text1'], $binding['text2'] -AppLogo $binding['image'] -ProgressBar $progress -UniqueIdentifier "toast" -DataBinding $binding foreach ($n in 1..100){ $binding['value'] = $binding['value'] + 0.01 Update-BTNotification -UniqueIdentifier "toast" -DataBinding $binding Start-Sleep 1 }
> 
> $绑定= @{ text 1 =“正在下载文件...” text 2 =“正在下载您的文件，以便脱机使用。” 值= 0 status =“正在下载...” } $progress = New-BTProgressBar -Status 'status' -Value 'value' New-BurntToastNotification -Text $binding['text1']，$binding['text2'] -AppLogo $binding['image'] -ProgressBar $progress -UniqueIdentifier“toast”-DataBinding $binding foreach（$n in 1.. 100）{ $binding['value'] = $binding['value'] + 0.01 Update-BTNotification -UniqueIdentifier“吐司”-DataBinding $binding 启动-睡眠1 }

I referenced the approach within this and made some modifications for you, and was able to implement the desired effect easily.： https://github.com/Windos/BurntToast/issues/120

**Comment by xianrui69** [comment]
> @xianrui69 thanks very much, I will try this today.
> 
> @xianrui69 非常感谢，今天我会试试这个。
> 
> I had already come up with a solution : https://stackoverflow.com/a/74225428/18427893
> 
> 我已经想出了一个解决方案：[https：//stackoverflow.com/a/74225428/18427893](https://stackoverflow.com/a/74225428/18427893)
> 
> Would you mind pointing out what has changed compared with my code ?
> 
> 你介意指出与我的代码相比有什么变化吗？

Bro, when you call binding, use the property name directly and make sure to use '-DataBinding $binding' at the beginning. No need to modify the following code.

**Comment by Silloky** [comment]
Ok, thanks for your help
