### ISSUE TITLE
Unable to launch application using custom button

### ISSUE THREAD

**Issue by jamesreedflinders** [Windos/BurntToast#22]
Trying to create a custom button that will launch an application but it doesn't appear to work. (SCCM Software Centre)

$audio1 = New-BTAudio -Source 'ms-winsoundevent:Notification.Reminder'
$visual1 = New-BTVisual -BindingGeneric $binding1
$button3 = New-BTButton -Content 'Launch App' -Arguments 'C:\Windows\CCM\ClientUX\SCClient.exe' -ActivationType Protocol 
$action3 = New-BTAction -Buttons $button3, $button4, $button5
$content1 = New-BTContent -Audio $audio1 -Visual $visual1 -Actions $action3 
Submit-BTNotification -Content $content1

Configuring the button to launch a URL works fine, however, if -Arguments is configured to a file path nothing happens when the button is clicked.

**Comment by ibrahimsharif** [comment]
Could you try to  pass  this line as arguments 

runas.exe /savecred /user:Domain\User " cmd /c start "C:\Users\iba\Desktop\yourEXEfilegoeshere.exe"                         

ActivationType Protocol Uses Windows Uri Scehma i think you could make you own entry




https://msdn.microsoft.com/en-us/library/aa767914(v=vs.85).aspx

**Comment by jamesreedflinders** [comment]
Thanks ibrahimsharif,

I wasn't able to get the above argument working, however, I did come across the 'Create your own URI' post when I originally tested this. I created a custom URI to launch the required app and it works fine. 

One of the scenarios we wanted to address was launch SCCM software centre, thankfully Microsoft already create a URI for this so we replace one of the arguments with $argument2 = 'softwarecenter://'

We took the information from the software center URI and created our own custom one.

**Comment by bbadger86** [comment]
> Creating a custom URI to launch a specific program does work. However, I found it cumbersome to create unique URI's for every unique action that I might like to call from a BT button.
> 
> For a generalized solution, I created a single custom URI that points to a locally staged instance of the PowerShell App Deployment Toolkit. Then I use the toolkit script to process the argument string that launched the protocol and take the necessary action. The way I designed my script, it can execute either an EXE or a PS1, with optional parameters in both cases.
> 
> With this, now I have a single setup routine to run on each client PC which does the following:
> 
> * Install BurntToast Module
> * Install custom AppID MSI
> * Configure the single custom URI
> * Stage the PS App Deploy Toolkit instance
> 
> And I can now launch any EXE or PS1 with parameters going forward without any other URIs to configure. I can whip out new notifications to my users with fully customized actions in no time now!
> 
> Note: If you're comfortable developing in Visual Studio, you could probably create a dedicated command line app to do the same thing, instead of using PSADT. I'm just far more comfortable with PowerShell.

Can you elaborate how you did this in PowerShell? I tried setting up a custom URI in registry - it's working everywhere else except when clicking the Toast Notification button.

**Comment by martinisoft1** [comment]
> Can you elaborate how you did this in PowerShell? I tried setting up a custom URI in registry - it's working everywhere else except when clicking the Toast Notification button. <

The same goes for me, doe you have some information on how you got this working?

**Comment by zebulun78** [comment]
> 
> 
> Creating a custom URI to launch a specific program does work. However, I found it cumbersome to create unique URI's for every unique action that I might like to call from a BT button.
> 
> For a generalized solution, I created a single custom URI that points to a locally staged instance of the PowerShell App Deployment Toolkit. Then I use the toolkit script to process the argument string that launched the protocol and take the necessary action. The way I designed my script, it can execute either an EXE or a PS1, with optional parameters in both cases.
> 
> With this, now I have a single setup routine to run on each client PC which does the following:
> 
>     * Install BurntToast Module
> 
>     * Install custom AppID MSI
> 
>     * Configure the single custom URI
> 
>     * Stage the PS App Deploy Toolkit instance
> 
> 
> And I can now launch any EXE or PS1 with parameters going forward without any other URIs to configure. I can whip out new notifications to my users with fully customized actions in no time now!
> 
> Note: If you're comfortable developing in Visual Studio, you could probably create a dedicated command line app to do the same thing, instead of using PSADT. I'm just far more comfortable with PowerShell.

Could you share how you created your custom URI and how you are passing that in the arguments?  I have also done everything you have listed here, and the URI works if launched in IE or other local methods, but NOT from this toast message.  Arggg....

**Comment by jholl016** [comment]
I didn't do anything special for the URI protocol handler. Refer to this documentation: https://msdn.microsoft.com/en-us/library/aa767914(v=vs.85).aspx

As for how I pass all the necessary information to the handler script, I do that by writing all the info to a formatted temp file (like xml or json). Then I pass that info file to the custom protocol, like custom protocol://path/to/my/settingsFile.xml.

Then my handler script reads the xml and executes the action with whatever parameters were specified.

**Comment by jholl016** [comment]
One thought... Toast actions have a couple of different supported types. Make sure you're using the protocol action type.

**Comment by rishabhnag1** [comment]
> > Can you elaborate how you did this in PowerShell? I tried setting up a custom URI in registry - it's working everywhere else except when clicking the Toast Notification button. <
> 
> The same goes for me, doe you have some information on how you got this working?

@martinisoft1 @bbadger86 Did either of you figure out how to run a powershell script through the button action? I have the URI command working fine everywhere other than the notification as well! Configured my URI command as follows
`powershell.exe -executionpolicy unrestricted -file <filename.ps1>`

**Comment by jholl016** [comment]
@rishabhnag1 Your PowerShell launch string does not constitute a valid URI. Please review the link in my comment above to familiarize yourself with URI creation and formatting.  In short, there is no way for you to call a PowerShell script directly from the toast. You have to create a handler app with a published URI protocol and pass your script to that handler.

**Comment by adamdriscoll** [comment]
I was able to achieve this with a batch script. 

Protocol handler command line

```
C:\ProgramData\BurntToast\BurntToast.cmd %1
```

BurntToast.cmd

```
powershell.exe -WindowStyle hidden -NonInteractive -ExecutionPolicy Bypass -NoLogo -NoProfile  -Command "& '%1'.Replace('powershell://', '').Trim('/')"
```

**Comment by Windos** [comment]
I demo'ed this at RTPSUG last week (video will be out at some stage, and code is on it's way to [their repo](https://github.com/rtpsug/Meetups/pull/12))

I was pointing it at a .ps1 file from the .cmd and trimming the protocol out of the string from inside the script... but I like your way better @adamdriscoll 

If people want this packaged up with a helper or two inside the BurntToast module, I can do that. Otherwise I plan on documenting the crap out of it.

**Comment by Windos** [comment]
In addition to protocol handlers, it's now possible to run any code via a toast notification action. This does require PowerShell 7.1 or above and BurntToast 0.8.0.

This [blog post](https://toastit.dev/2020/08/08/actionable/) shows it in action, though with v0.8.0 it's a lot easier to take advantage of this via some new parameters on New-BurntToastNotification and Submit-BTNotification. Documentation for this is  coming soon, for now check out the end of this [live stream](https://youtu.be/8TuqVs7QGz0).
