### ISSUE TITLE
New-BurntToastNotification Button Overflow Menu

### ISSUE THREAD

**Issue by stevesec** [Windos/BurntToast#223]
## Summary of the new feature/enhancement

As a user, I would like to see an overflow menu of the varying options with buttons. Right now, there are only 4 options allowed within the notification tile. 

## Proposed technical implementation details (optional)

With the New-BurntToastNotification, allow for more than 4 buttons in an overflow state (i.e., in a dropdown or buttons on top of one another).

**Comment by Windos** [comment]
Unfortunately, limitations like this are imposed by Microsoft via the Notifications API and isn't something that can be overcome when using that API (which this module does).
