### ISSUE TITLE
Launch Url from toast

### ISSUE THREAD

**Issue by cnich123** [Windos/BurntToast#24]
In C# I can designate the properties "Launch and ActivationType" like so:

var toastContent = new ToastContent()
            {
                Visual = new ToastVisual()
                {
                    BindingGeneric = new ToastBindingGeneric()
                    {
                        Children =
            {
                new AdaptiveText()
                {
                    Text = itemTitle
                },
                new AdaptiveText()
                {
                   //Text = itemGuid
                }
            },
                        Attribution = new ToastGenericAttributionText()
                        {
                            Text = "Pima County"
                        }
                    }
                },
                **Launch = itemGuid.ToString(),
                ActivationType = ToastActivationType.Protocol**
            };

This allows me to click the notification and it will bring up the Url. Is this something that can be done? Also, this is great stuff! Keep up the good work!

**Comment by Windos** [comment]
You certainly can! You'll need to dip into the "advanced" functions, beyond just the `New-BurntToastNotification` function.

I've done a [blog post](https://king.geek.nz/2017/05/08/crouton-clickable/) on this, but to just transplant some example code here for completeness:

```
$Text1 = New-BTText -Content 'Google!'
$Text2 = New-BTText -Content 'Clicking this will open Google.'
$Binding1 = New-BTBinding -Children $Text1, $Text2
$Visual1 = New-BTVisual -BindingGeneric $Binding1

$Content1 = New-BTContent -Visual $Visual1 -Launch 'https://google.com' -ActivationType Protocol

Submit-BTNotification -Content $Content1
```

Results:

![toastclick](https://user-images.githubusercontent.com/6955786/33191080-f6499100-d119-11e7-981d-0f07c1cbebb4.gif)
