### ISSUE TITLE
SnoozeAndDismiss not appearing in Fall Creators Update

### ISSUE THREAD

**Issue by Clizby** [Windos/BurntToast#25]
Using -SnoozeAndDismiss options, no buttons appear.  Coworker on Spring Creators Update does have the buttons appearing.  Custom buttons appear to be working fine.

**Comment by Windos** [comment]
Thanks for the report, I can reproduce on my machine(s). Will aim to have a fix in the next release!

**Comment by Windos** [comment]
Unfortunately it turned out that this was an issue with the Windows APIs and I couldn't work around it. This means I can't bake a fix into the code and rather it's a case of updating (or downgrading) Windows if one must use the Snooze and Dismiss options with BurntToast.
