### ISSUE TITLE
Get ItemBox selected item

### ISSUE THREAD

**Issue by Chrisotphe31140** [Windos/BurntToast#26]
Hello all, 

I'm working on a toast notification where I have to get the item of a list box selected by the user.

Currently, my notification looks well but I don't know how to retrieve the user choice ...

Is it on the "Arguments" property of the button that I have to play?

My code: 

`$Content = $null

$Select1 = New-BTSelectionBoxItem -Id 'Item1' -Content 'Choice 1'
$Select2 = New-BTSelectionBoxItem -Id 'Item2' -Content 'Choice 2'
$Select3 = New-BTSelectionBoxItem -Id 'Item3' -Content 'The good choice'

$list = New-BTInput -Id 'Selection001' -Items $Select1, $Select2, $Select3 -Title "Liste of choices" -DefaultSelectionBoxItemId "Item3"

$text = New-BTText -Text "hello"

$Binding = New-BTBinding -Children $text

$Visual = New-BTVisual -BindingGeneric $Binding

$Audio = New-BTAudio -Source ms-winsoundevent:Notification.Default

$button = New-BTButton -Content "Button" -Arguments "???"

$action = New-BTAction -Inputs $list -Buttons $button

$Content = New-BTContent -Visual $Visual -Actions $action

Submit-BTNotification -Content $Content
`

If someone knows how to make it work it will be very appreciated :)

Thank you

**Comment by Windos** [comment]
Unfortunately, I *think* this will be one of the "missing links" we run into because of not being able to subscribe to WinRT event in PowerShell. i.e. We can make these selection boxes... but can't really **do** anything with them.

I'll certainly look into though, it's possible something changed in the Fall Creators Update that will help bridge this gap.

**Comment by itpropro** [comment]
As far as I understand, this and receiving text input will not be possible, as we would need to handle activation or background activation. Therefore in an native UWP app, we would need to create an override for OnActivated/OnBackgroundActivated and need to be able to configure the BackgroundExecutionManager. As the AppId of PowerShell is used, this cannot be done. 
As an alternative for Win32 apps, it would be necessary to use the compat library from the Windows 10 SDK, Register a COM activator and to extend the NotificationActivator class with an override for the OnActivated method.
Additionally there is code that needs to be added to register AUMID and COM server.

If anyone has an idea, how to implement this in PowerShell, I would be happy to support.
Here is the docs link for the Win32 implementation: https://docs.microsoft.com/en-us/windows/uwp/design/shell/tiles-and-notifications/send-local-toast-desktop

**Comment by Windos** [comment]
This is now possible! See here for an example: https://toastit.dev/2020/08/08/actionable/

Better documentation is coming, but feel free to open a discussion if you're trying to crack a specific use case!
