### ISSUE TITLE
Access Denied

### ISSUE THREAD

**Issue by kanudas** [Windos/BurntToast#27]
Hello!
I seem to be getting an error when executing BurntToast:

Exception calling "Show" with "1" argument(s): "Access denied. (Exception from HRESULT: 0x80070005 (E_ACCESSDENIED))"
At C:\WINDOWS\system32\config\systemprofile\Documents\WindowsPowerShell\Modules\BurntToast\0.6.1\Public\Submit-BTNotific
ation.ps1:70 char:5
+     [Windows.UI.Notifications.ToastNotificationManager]::CreateToastN ...
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : UnauthorizedAccessException
Exception calling "Show" with "1" argument(s): "Access denied. (Exception from H
RESULT: 0x80070005 (E_ACCESSDENIED))"
At C:\WINDOWS\system32\config\systemprofile\Documents\WindowsPowerShell\Modules
\BurntToast\0.6.1\Public\Submit-BTNotification.ps1:70 char:5
+     [Windows.UI.Notifications.ToastNotificationManager]::CreateToastN ...
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : UnauthorizedAccessException

I'm running the script as local system account

EDIT: Wrong logfile

**Comment by Windos** [comment]
Hey @kanudas! What version of Windows 10 are you on?

Also, do you get this when you run the script as yourself? I *think* (though I'll have to test myself to make sure) that this is expected when running as the system or other non-"user" accounts as they don't have a Windows UI through which to display the toast.

You may need to invoke a powershell session as your logged in user account if you **have** to run the rest of the script as a system account.

**Comment by kanudas** [comment]
Hello Windos!
Thanks alot for the quick respons:
Version 1709, 64 bit.
When I run the script myself it works fine.

Regards to the respons about the Windows UI. This is true!
I am executing the script trough PSEXEC:

ost Application: PowerShell -windowstyle hidden -file script.ps1

As well the local system account does have a Windows desktop of its own(Just that you can't see it). Meaning applications that require GUI to popup works on system account(Just that you can't see it).
So I don't think I should get an error? I just just not see anything.

Also I've been able to popup toast on my desktop trough system account, just not with BurntToast, but I would like to get it working with BurntToast since it a complete module with very nice features.

It just somehow seems to hang on the fact that "Denied access" error on [Windows.UI.Notifications.ToastNotificationManager]

Looking forward to your respons
Best Regards, Kanudas

**Comment by kanudas** [comment]
Hello @Windos!
Terribly Sorry to be bothering you once again, I do hope I'm not interlopeing or becoming a source of irritance.
I was wondering perhaps if you would have any notion regarding the issue I presented, if it is related to the actions I've chosen to take with it or regarding the module itself.
Looking forward to your respons
Best Regards, Kanudas

**Comment by grandmasterv** [comment]
Hello,

I'm having the same issue.  I'm trying to use your module to notify all logged in users but if I do not invoke it using a specific users credentials it does not show up.  If I use the system account I get the permission error above.  I'd love to see a solution for easily creating notifications for all logged in users on the system.  I'm trying to use this module instead of the old `msg.exe` command.  I think this is a feature request and not a bug.

Thanks!

**Comment by mingyar** [comment]
Hi! The same is happening to me:

Exception calling "Show" with "1" argument(s): "Access is denied. (Exception from HRESULT: 0x80070005
(E_ACCESSDENIED))"
At C:\Program Files\WindowsPowerShell\Modules\BurntToast\0.6.3\BurntToast.psm1:1641 char:9
+         [Windows.UI.Notifications.ToastNotificationManager]::CreateTo ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : UnauthorizedAccessException

Thanks.

**Comment by pabmart** [comment]
Hi, The same issue when I deploy the script via SCCM.
The script run with System account

>> ParameterBinding(Out-String): name="InputObject"; value="Exception calling "Show" with "1" argument(s): "Access is denied. (Exception from HRESULT: 0x80070005 (E_ACCESSDENIED))""
Exception calling "Show" with "1" argument(s): "Access is denied. (Exception from HRESULT: 0x80070005 (E_ACCESSDENIED))"
At C:\Program Files\WindowsPowerShell\Modules\BurntToast\0.6.3\BurntToast.psm1:1641 char:9
+         [Windows.UI.Notifications.ToastNotificationManager]::CreateTo ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : UnauthorizedAccessException


Process ID: 15460
PSVersion: 5.1.17763.134
PSEdition: Desktop
PSCompatibleVersions: 1.0, 2.0, 3.0, 4.0, 5.0, 5.1.17763.134
BuildVersion: 10.0.17763.134
CLRVersion: 4.0.30319.42000
WSManStackVersion: 3.0
PSRemotingProtocolVersion: 2.3
SerializationVersion: 1.1.0.1

A running script without SCCM works very well
Many thanks

**Comment by jwood79** [comment]
I'm getting the following error when running under my admin credentials and running it locally.

Exception calling "Show" with "1" argument(s): "Access is denied. (Exception from HRESULT: 0x80070005 (E_ACCESSDENIED))"
At C:\Program Files\WindowsPowerShell\Modules\BurntToast\0.6.3\BurntToast.psm1:1641 char:9
+         [Windows.UI.Notifications.ToastNotificationManager]::CreateTo ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : UnauthorizedAccessException

**Comment by Ig3l** [comment]
Hey there,

i am doing the following to start the toast as System in the users context:


$server = [System.Net.Dns]::GetHostByName($env:computerName).HostName
        Invoke-Command -ComputerName $server -ScriptBlock { New-BurntToastNotification } 

If you want to use variables in the ScriptBlock you have to use the -Argumentlist or by using the $using: variable.

**Comment by ztrhgf** [comment]
Same access denied issue here. Maybe the code should be rewritten using:

Add-Type -AssemblyName System.Windows.Forms
$global:balmsg = New-Object System.Windows.Forms.NotifyIcon
$path = (Get-Process -id $pid).Path
$balmsg.Icon = [System.Drawing.Icon]::ExtractAssociatedIcon($path)
$balmsg.BalloonTipIcon = [System.Windows.Forms.ToolTipIcon]::Warning
$balmsg.BalloonTipText = ‘This is the pop-up message text for the Windows 10 user'
$balmsg.BalloonTipTitle = "Attention $Env:USERNAME"
$balmsg.Visible = $true
$balmsg.ShowBalloonTip(20000)

This works on my system under logged user and also from console started using runas (under different user)

**Comment by Windos** [comment]
The easiest thing to do if you can't run the toast as the interactive user is to run it through @KelvinTegelaar's [RunAsUser](https://github.com/KelvinTegelaar/RunAsUser) module.

Kelvin has a [blog post](https://www.cyberdrain.com/monitoring-with-powershell-notifying-users-of-windows-updates/) showing it in action, the use case in mind here is that the script is running as SYSTEM via an RMM tool but obviously the toast needs to come through in the user context.

Another tool you can use is @mkellerman'a [Invoke-CommandAs](https://github.com/mkellerman/Invoke-CommandAs).

**Comment by davidsteimle** [comment]
This may very well be a system based permissions issue. I have been using a non-BurntToast method (sorry) and get the same error from ``Show()`` method on the ``Windows.UI.Notifications.ToastNotificationManager`` object. Ran on a few machines in my Enterprise with the noted error. Sent the script to my personal machine and it ran perfectly.

**Comment by darkpixel** [comment]
The RunAsUser repo doesn't have issues enabled, the repo has recent commits, but the latest version on PSG is 18 months out of date, and the solution doesn't work for me:

```
        Invoke-AsCurrentUser : Could not execute as currently logged on user: Exception calling "StartProcessAsCurrentUser" 
        with "7" argument(s): "CreateProcessAsUser failed. (Access is denied, Win32ErrorCode 5 - 0x00000005)"
```

**Comment by KelvinTegelaar** [comment]
The runasuser repo purposely has issues disabled; there's too many begging choosers *demanding* support. As it's an open source project. Feel free to dissect the code and make the changes you need really.

**Comment by darkpixel** [comment]
Got it.  Maybe post something in your README that says "works for me, if it doesn't work for you, GFY".
Knowing the project has that attitude, I wouldn't have wasted several hours coming up with a fix.

**Comment by KelvinTegelaar** [comment]
Never said anything like that, but if you think being rude helps your case, it doesn't:) good luck on your endevours though!

**Comment by darkpixel** [comment]
It's not my intent to be rude.  My intent was to debug and potentially fix the problem, then share it to help everyone, but your repo and your attitude appear to be that you're shutting down any and all collaboration because some people apparently "demand" help.  That's fine.  That's your choice.
