### ISSUE TITLE
install.ps1 isn't idempotent

### ISSUE THREAD

**Issue by sonjz** [Windos/BurntToast#3]
I'm rerunning the install.ps1 in a deployment script, but it doesn't appear to gracefully handle if BurntToast has already been installed:

```
# command
iex ((New-Object net.webclient).DownloadString('https://raw.githubusercontent.com/Windos/BurntToast/master/install.ps1')) ;

```

Have you thought about putting this into chocolatey?  Its a great tool.

![image](https://cloud.githubusercontent.com/assets/1714763/16049197/2f11ad16-322d-11e6-94ee-40f0d3af2ec8.png)

**Comment by sonjz** [comment]
`Expand-Archive BurntToast.zip -force` should fix it.
Also, you might also want to add a flag to install.ps1 or consider adding the module system wide vs a user profile:

https://msdn.microsoft.com/en-us/library/dd878350(v=vs.85).aspx
"$Env:ProgramFiles\WindowsPowerShell\Modules\"

I'm using the notification from a Scheduled Task that is run as SYSTEM, I'm guessing this might be a common scenario.

**Comment by Windos** [comment]
Strictly speaking, the install.ps1 file is there more for a quick and dirty install for testing if you don't feel like downloading off of the GitHub site manually and copying the contents to wherever.

It is up on the [PowerShell Gallery](http://www.powershellgallery.com/packages/BurntToast), which is probably the better way to achieve a reliable (and customizable) install: `Install-Module -Name BurntToast`

Adding the `-force` parameter should skip any prompts, allowing for an unattended install (though it will also re-install the module if it is already on the system.)

In saying that I'll add some error handling and the like to make it a bit more usable.

**Comment by sonjz** [comment]
Thanks, sounds good, I'll use install-module to deploy.
