### ISSUE TITLE
Doesn't seem to be a way to use a custom .WAV for a notification

### ISSUE THREAD

**Issue by 1RedOne** [Windos/BurntToast#30]
Hi!

[Re: this thread on reddit](https://www.reddit.com/r/FoxDeploy/comments/88ggpm/help_using_burnttoast_in_powershell/).  I noticed there doesn't seem to be a way to use my own .WAV along with a Burnt Toast noticiation.  

If this is a supported scenario, could it be added to the help?  I noticed that when I try to specify my own Audio file like so:

    $oink = 'C:\Users\Stephen\Downloads\snort.wav'
    $pigSound = New-BTAudio -Path $oink 

    New-BurntToastNotification -Sound $pigSound -Text 'ham'

`New-BTAudio` returns an object like so, but I am not sure how to use that as a param for `New-BurntToastNotification`.

    Src                                           Loop Silent
    ---                                           ---- ------
    file:///C:/Users/Stephen/Downloads/snort.wav False  False

When we try to use it, we see the following:

```
New-BurntToastNotification -Sound $pigSound -Text 'ham'
New-BurntToastNotification : Cannot validate argument on parameter 'Sound'. The argument "Microsoft.Toolkit.Uwp.Notifications.ToastAudio" does 
not belong to the set "Default,IM,Mail,Reminder,SMS,Alarm,Alarm2,Alarm3,Alarm4,Alarm5,Alarm6,Alarm7,Alarm8,Alarm9,Alarm10,Call,Call2,Call3,Call4,
Call5,Call6,Call7,Call8,Call9,Call10" specified by the ValidateSet attribute. Supply an argument that is in the set and then try the command 
again.

```

I tried modifying the cmdlet and removing the ValidateSets because they prohibit me from feeding in a newly created object, but couldn't figure out the syntax.

**Comment by Windos** [comment]
Cheers Stephen! Jim also got in touch via Twitter.

For completeness sake, just in case anyone has the same issue and find this page when searching, I'll put the gist of the situation here...

`New-BurntToastNotification` is more or less the "basic" function for creating Toasts. It's meant to provide a short runway for getting off the ground quickly. I've tried to limit the number of parameters on it as much as possible (it's already a sea of parameter sets!)

There are 15 "advanced" functions also included as part of the module for doing anything that the basic function doesn't allow.

Specifically, to replicate the default Toast from the basic function, you'd need to do the following with the advanced ones:

```
$Text1 = New-BTText -Content 'Default Notification'
$ImagePath = Join-Path -Path (Get-Module BurntToast -ListAvailable).ModuleBase -ChildPath 'Images\BurntToast.png'
$Image1 = New-BTImage -Source $ImagePath -AppLogoOverride -Crop Circle
$Audio1 = New-BTAudio -Source 'ms-winsoundevent:Notification.Default'

$Binding1 = New-BTBinding -Children $Text1 -AppLogoOverride $Image1
$Visual1 = New-BTVisual -BindingGeneric $Binding1
$Content1 = New-BTContent -Visual $Visual1 -Audio $audio1

Submit-BTNotification -Content $Content1
```

Full write up over [on my blog](https://king.geek.nz/2018/04/02/crouton-sounds/).
