### ISSUE TITLE
0.62 Submit-BTNotification not working on April 2018 Update (1803)

### ISSUE THREAD

**Issue by brannbrann** [Windos/BurntToast#32]
A couple of issues, actually, with the April Win10 update 1803 where Submit-BTNotification runs successfully, but no toast is displayed. Wondering if anybody else is having this issue? The script ran fine up to 1709 with BT 0.61, but 1803 seems to have changed something. We have BT notification scripts running as a scheduled task in system context, but even as admin user context no toasts are displayed.

New-BurntToastNotification does run and creates a toast in the notification center, but doesn't pop out.

Anybody else seen this?

**Comment by Windos** [comment]
Hey @brannbrann, I'm guessing by the title that you've updated BurntToast to v0.6.2?

What is your AppId set to (you'll find this in the config.json file inside the module directory)?

Is Focus Assist turned on?

Also, head into Settings -> System -> Notifications & actions then scrolls down and check that the application isn't turned off?

**Comment by brannbrann** [comment]
Hi Windos, thanks for the reply! I'm just testing .62, and am using .61 currently. Yes, we are using a custom AppId, which looks to be the problem. That's an easy fix, so we're back in business.

The bulk of our fleet is on 1607, but we're beginning to update to 1803, so we'll need to figure out something for the faded notification situation.

I've done a little digging and found a few things. New-BTAppId creates the regkey for the custom AppId, but it does not show in Notifications & alerts, so no way to turn it on or off. I dunno.

There's a new feature in 1803, Focus Assist (or at least a renamed Quiet Hours), which was set to alarms only as default, which suppresses popups. It doesn't look like there's a regkey for the setting, but it's also quite possible that I missed it.

Otherwise, thanks again.

**Comment by Windos** [comment]
I've got a work around for the AppId thing here: https://king.geek.nz/2018/03/03/burnttoast-wix/

It's not pretty but it works, however I'm not sure it's salable if you're doing this over an entire network.

In short you basically create an MSI installer using WiX, this ends up putting a shortcut in the start menu with a valid AppId. Use that AppId in BurntToast and they won't be grayed out any more.


... I'm still working on a better solution.

**Comment by brannbrann** [comment]
Thanks again. Yes, I think we'll go the MSI route!
