### ISSUE TITLE
Fresh Install, lots of red

### ISSUE THREAD

**Issue by steviecoaster** [Windos/BurntToast#34]
Hey, just as a heads up. I put a fresh copy of BurntToast on my machine for use in the upcoming PowerHour, and I get a slew of red text when trying to use it:

```
Exception calling "GetContent" with "0" argument(s): "Could not load file or assembly 'System.Xml.ReaderWriter, Version=4.1.0.0,
Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified."
At C:\Program Files\WindowsPowerShell\Modules\BurntToast\0.6.2\BurntToast.psm1:1582 char:5
+     $CleanContent = $Content.GetContent().Replace('<text>{', '<text>' ...
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : FileNotFoundException

You cannot call a method on a null-valued expression.
At C:\Program Files\WindowsPowerShell\Modules\BurntToast\0.6.2\BurntToast.psm1:1583 char:5
+     $CleanContent = $CleanContent.Replace('}</text>', '</text>')
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : InvokeMethodOnNull

You cannot call a method on a null-valued expression.
At C:\Program Files\WindowsPowerShell\Modules\BurntToast\0.6.2\BurntToast.psm1:1584 char:5
+     $CleanContent = $CleanContent.Replace('="{', '="')
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : InvokeMethodOnNull

You cannot call a method on a null-valued expression.
At C:\Program Files\WindowsPowerShell\Modules\BurntToast\0.6.2\BurntToast.psm1:1585 char:5
+     $CleanContent = $CleanContent.Replace('}" ', '" ')
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : InvokeMethodOnNull

Exception calling "LoadXml" with "1" argument(s): "Exception from HRESULT: 0xC00CE558"
At C:\Program Files\WindowsPowerShell\Modules\BurntToast\0.6.2\BurntToast.psm1:1587 char:5
+     $ToastXml.LoadXml($CleanContent)
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : Exception

Exception calling "Show" with "1" argument(s): "The parameter is incorrect.

The parameter is incorrect.
"
At C:\Program Files\WindowsPowerShell\Modules\BurntToast\0.6.2\BurntToast.psm1:1600 char:5
+     [Windows.UI.Notifications.ToastNotificationManager]::CreateToastN ...
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : ArgumentException
```
Sample command to reproduce:

`New-BurntToastNotification -Text "Test"`

**Comment by Windos** [comment]
Hey Stephen, what version of Windows and which version of PowerShell are
you running?

**Comment by steviecoaster** [comment]
Windows 10 1803


Name                           Value                                                                                   
----                           -----                                                                                   
PSVersion                      5.1.15063.1155                                                                          
PSEdition                      Desktop                                                                                 
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                 
BuildVersion                   10.0.15063.1155                                                                         
CLRVersion                     4.0.30319.42000                                                                         
WSManStackVersion              3.0                                                                                     
PSRemotingProtocolVersion      2.3                                                                                     
SerializationVersion           1.1.0.1

**Comment by Windos** [comment]
Huh, that's weird. Out of interest was this the same session it was
installed during (and does it still do it in a new session)?

Also, how was it installed? Gallery or Zip from GitHub?

**Comment by steviecoaster** [comment]
Yes, during and after the result is the same.

`Install-Module BurntToast -Force` is what I used to grab it from the Gallery.

**Comment by steviecoaster** [comment]
I'm on Slack if you wanna DM me if it is easier.

**Comment by Arkevius** [comment]
I got the same exact error after installing. After much confusion and frustration, I was able to remedy this by creating a new folder under the module's lib directory for the 'missing' System.Xml.ReaderWriter library, and placed a copy of the dll in there.
After re-importing the BurntToast module and sending a toast, I no longer receive that error.

Win10 1703 (Build 15063.1324)
Powershell 5.1.15063.1292

**Comment by chickentech** [comment]
I'm also seeing this same issue - I'll try @Arkevius proposed solution.

**Comment by Windos** [comment]
In working with @steviecoaster, this ended up being an issue of using a .NET Core version of the UWP Toolkit, rather than one of the other options...

I'll be swapping them out in the next release.

**Comment by SoftwareNinja** [comment]
Having the same issue, but I can't seem to find that UAP10.0 DLL anywhere. You wouldn't happen to have any references to that one @Arkevius ?

**Comment by Arkevius** [comment]
@SoftwareNinja 
Download the NuGet package from the site (right-hand side under Info)
https://www.nuget.org/packages/Microsoft.Toolkit.Uwp.Notifications/5.0.0
Open the nupkg as an archive (7-zip for example) and drill down to lb > uap10.0 folder.
The DLL you want is there.

**Comment by Wand3rvogel** [comment]
Is this already fixed?
```
Install-Module BurntToast
New-BurntToastNotification
Exception calling "GetContent" with "0" argument(s): "Could not load file or assembly 'System.Xml.ReaderWriter,
Version=4.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find
the file specified."
At C:\Program Files\WindowsPowerShell\Modules\BurntToast\0.6.2\BurntToast.psm1:1582 char:5
```
Happy New Year! :)

**Comment by PaulSIsaac** [comment]
As per Wand3rvogel's question. As this been fixed yet in 0.6.2? Only I get the same error and had to perform that same fix to get it working, which, although doable is less than ideal. 

Thanks,

Paul

**Comment by Windos** [comment]
Hey all, sorry I've not been seeing notifications about this issue (I've just tried resubscribing to it so fingers crossed).

I've not yet pushed an update, but this will be fixed in the next release.

**Comment by Windos** [comment]
@steviecoaster, @PaulSIsaac, @Wand3rvogel 

I just pushed an update [(v0.6.3)](https://www.powershellgallery.com/packages/BurntToast/0.6.3) which includes the change in the dll mentioned in this thread. Any chance you're able to check that this new version works on your end?

**Comment by Wand3rvogel** [comment]
Works, thanks.

**Comment by Windos** [comment]
Thanks @Wand3rvogel 

Closing this for now, from talking to a few folks this sounds like it's sorted the issue.

If it happens again, please do let me know!

**Comment by JeshuaEdgar** [comment]
Re-opening this because I am get the same error, I tried @Arkevius 's approach by replacing the DLL without any success.

This is the PSVersion of the specific machine the errors occur on:
```
Name                           Value
----                           -----
PSVersion                      5.1.19041.1
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.19041.1
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

And the exact errors I am getting:
```
Exception calling "GetContent" with "0" argument(s): "Source property is required."
At C:\Users\x\Documents\WindowsPowerShell\Modules\BurntToast\0.8.3\BurntToast.psm1:873 char:91
+ ... ontent.GetType().Name)] with XML: $($ToastContent.GetContent())" )) {
+                                         ~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : NullReferenceException
 
Exception calling "GetContent" with "0" argument(s): "Source property is required."
At C:\Users\x\Documents\WindowsPowerShell\Modules\BurntToast\0.8.3\BurntToast.psm1:2328 char:9
+         $CleanContent = $Content.GetContent() -Replace '<text(.*?)>{' ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : NullReferenceException
 
You cannot call a method on a null-valued expression.
At C:\Users\x\Documents\WindowsPowerShell\Modules\BurntToast\0.8.3\BurntToast.psm1:2329 char:9
+         $CleanContent = $CleanContent.Replace('}</text>', '</text>')
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : InvokeMethodOnNull
 
You cannot call a method on a null-valued expression.
At C:\Users\x\Documents\WindowsPowerShell\Modules\BurntToast\0.8.3\BurntToast.psm1:2330 char:9
+         $CleanContent = $CleanContent.Replace('="{', '="')
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : InvokeMethodOnNull
 
You cannot call a method on a null-valued expression.
At C:\Users\x\Documents\WindowsPowerShell\Modules\BurntToast\0.8.3\BurntToast.psm1:2331 char:9
+         $CleanContent = $CleanContent.Replace('}" ', '" ')
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : InvokeMethodOnNull
 
Exception calling "LoadXml" with "1" argument(s): "Uitzondering van HRESULT: 0xC00CE558"
At C:\Users\x\Documents\WindowsPowerShell\Modules\BurntToast\0.8.3\BurntToast.psm1:2333 char:9
+         $ToastXml.LoadXml($CleanContent)
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : Exception
 
Exception calling "GetContent" with "0" argument(s): "Source property is required."
At C:\Users\x\Documents\WindowsPowerShell\Modules\BurntToast\0.8.3\BurntToast.psm1:2427 char:171
+ ...  $($Toast.Data.SequenceNumber) and XML: $($Content.GetContent())")) {
+                                               ~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : NullReferenceException
 
Exception calling "Show" with "1" argument(s): "De parameter is onjuist.
De parameter is onjuist.
"
At C:\Users\x\Documents\WindowsPowerShell\Modules\BurntToast\0.8.3\BurntToast.psm1:2428 char:9
+         [Windows.UI.Notifications.ToastNotificationManager]::CreateTo ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : ArgumentException
 
```

Testing on multiple machines I get mixed results, some work, some display this error message. Tried replacing the DLL on several machines where this error occurs, any tips?

Thanks in advance
