### ISSUE TITLE
Invoking BurntToast in ooRexx on Windows 10

### ISSUE THREAD

**Issue by RockFox** [Windos/BurntToast#4]
[BurntToast.rex.txt](https://github.com/Windos/BurntToast/files/390871/BurntToast.rex.txt)

I am successfully calling BurntToast from an ooRexx program -- see attached.  But I had problems getting it to work.  I kept getting a message that 'Get-StartApps' was not a valid cmdlet...

So I edited New-BurntToastNotification.ps1 line 117 and made it a comment:
# [String] $AppId = ( ((Get-StartApps -Name '_PowerShell_') | Select-Object -First 1).AppId ),

and changed line 118 from blank to:
[String] $Appid = '_PowerShell_', 
all is well now and I'm very happy with BurntToast..

What is the purpose of line 117?  Will I run into trouble without it?

I need a little help -- I can't figure out how to specify my own image without changing the default in the source.

**Comment by Windos** [comment]
It used to be that case that these wouldn't work unless you pulled a 'real' appid from the startmenu. The one for PowerShell on my machine comes back as `{1AC14E77-02E7-4E5D-B744-2EB1AE5198B7}\WindowsPowerShell\v1.0\powershell.exe`.

I'm re-writing BurntToast for Windows 10 specifically (there's enough new features that aren't available in 8.1 that targeting both isn't too feasible for me any more.)
