### ISSUE TITLE
Pop-ups always include "Windows Powershell"

### ISSUE THREAD

**Issue by thorstenkampe** [Windos/BurntToast#49]
Pop-ups always include the "Windows Powershell" "trademark" (see below). Is it possible to disable that?
![image](https://user-images.githubusercontent.com/475462/47523148-a8e45e00-d897-11e8-8f55-c0a14dfd8b87.png)

**Comment by Windos** [comment]
That's coming from the AppId, the only way to "remove" it is to not have a custom app logo on the left hand side (where that "i" is)... but then you'll see the little icon for PowerShell there instead.

You can change it to something else, but it requires running (and possibly building) an MSI to drop a shortcut into your start menu:

PrePrepared BurntToast installer (though this will result in "Windows PowerShell" being replaced by "BurntToast:: https://king.geek.nz/2018/02/04/burnttoast-appid-installer/
Custom Installer: https://king.geek.nz/2018/03/03/burnttoast-wix/

**Comment by cdric0701** [comment]
Hello, I haven't really understood the solution ... Is there a simple solution to change the logo and the Trademark to something custom ? Thanks

**Comment by elig0n** [comment]
I have installed BurntToast MSI and modified config.json according to instructions yet it doesn't change.
Windows 10 19043.1288
