### ISSUE TITLE
New-BTButton with logo/image

### ISSUE THREAD

**Issue by cdric0701** [Windos/BurntToast#51]
Hello !
Thanks for this great repository, well documentated.
I am trying to display buttons on the Toast Alert.
I managed to display with 
```
$Button1 = New-BTButton -Content 'bien' -Arguments 'https://google.com'
New-BurntToastNotification -Text "How are you doing ?" -Button ($Button1)
```

However I would like to display my button with a little image/logo on it, is it possible ?
Thanks in advance

**Comment by Windos** [comment]
Hey @cdric0701, absolutely!

Put the path to your desire image on the "ImageUri" parameter for `New-BTButton`:

```powershell
$Button1 = New-BTButton -Content 'bien' -Arguments 'https://google.com' -ImageUri 'C:\Users\windos\Documents\GitHub\BurntToast\Media\BurntToast-Logo.png'
New-BurntToastNotification -Text "How are you doing ?" -Button $Button1
```

Exactly how this displays differs based on your version of Windows 10. It used to appear to the left of the next, but it's now above:

![button with image](https://user-images.githubusercontent.com/6955786/48924644-7cb40f80-ef1f-11e8-9044-0c7f8900b69b.PNG)

**Comment by cdric0701** [comment]
Oh thanks ! Great !
Problem resolved
