### ISSUE TITLE
Can this be used for In-place Upgrades within MDT or ConfigMgr for OSD?

### ISSUE THREAD

**Issue by Mrgreen17** [Windos/BurntToast#53]

**Comment by Windos** [comment]
I'm not in a position to be able to try it out myself, but... maybe? Check out this article from @SMSAgentSoftware: https://smsagent.blog/2018/06/15/using-windows-10-toast-notifications-with-configmgr-application-deployments/

Trevor's code includes all the XML and related code for generating the toast, you *could* use BurntToast to make that part easier (no hard feeling if you don't, lol!) But it looks like the key is the Software Center Shortcut, which you can put behind a button or the click action of the toast itself.
