### ISSUE TITLE
Dynamically Updating Toasts

### ISSUE THREAD

**Issue by ShadoKima** [Windos/BurntToast#54]
Is it possible to update a toast (by using a unique identifier) without refreshing the entire toast? forgive my ignorance if i have overlooked some part of the documentation.

**Comment by Windos** [comment]
Hey @ShadoKima, not yet. I'm hoping to have this sorted for the next release

**Comment by Windos** [comment]
This is sorted and will be out in the next release, 0.7.0

The actual mechanics of is requires a little explanation, and I'm not sure I'll be able to do the topic justice in the comment based help... so there will certainly be a blog post or two on this.

The function to keep an eye out for is `Update-BTNotification`

**Comment by AmineI** [comment]
Didn't notice it it in the releases notes so I thought it was delayed - I'll work on migrating my old mass-toasts to only one that's dynamically updated, thanks !
