### ISSUE TITLE
Use of AppLogo from network

### ISSUE THREAD

**Issue by cdric0701** [Windos/BurntToast#56]
Hello !
Is it possible to use an -AppLogo from the network ?

For example:
\\np1\Users\Public\image-notif.gif
It doesn't seems to work ... how can I do that ?

Thanks

**Comment by Windos** [comment]
Just had a look, and can reproduce this issue... will dive in and see if I can make this work on the next release.

**Comment by Windos** [comment]
It looks like the same sort of problem as with [URIs to online images](https://king.geek.nz/2018/05/28/downloading-an-image-for-local-use/) where the documentation says it works... but it doesn't.

I plan to put a work around in as before to copy the image from the network path to the local temp directory.

**Comment by Windos** [comment]
This will be out in v0.7.0... soon(tm)
