### ISSUE TITLE
Get-BurnToast

### ISSUE THREAD

**Issue by tedkol** [Windos/BurntToast#62]
Feature Request:

Get-BurntToastNotification - retrieve all notifications from the notification center.

**Comment by Windos** [comment]
Sounds like a good idea, I'll see what I can do

**Comment by Windos** [comment]
Here's what I've found I can do:

List all notifications from a given AppId (generally all of the toasts from this module will be under the same banner.)

Clear all notifications from a given AppId

Clear a specific toast (based on unique identifier)

All looks good and will be in the next release! Thanks again for the suggestion

**Comment by jwood79** [comment]
I like this feature. 

I will be creating a notification every 30 minutes if a PC needs a reboot and it would be great if before iT created one, it checks to see if one is already there and closes it. That way there will not be a lot of notifications sitting there.

**Comment by Windos** [comment]
v0.7.0 will have functions for getting, and clearing toasts:

Get-BTHistory
Remove-BTNotification

These are feature complete, but need comment based help. Regardless, keep an eye out for the next release... soon(tm)

**Comment by AmineI** [comment]
Does Get-BTHistory also gets the notification's text/content ? That would allow, along with `-UniqueIdentifier` to manually add information to a toast :)

**Comment by Windos** [comment]
It returns an object which includes the xml (which you can inspect to see
the content), any bindable text (this is a whole topic in and of itself).

The object also has the tag and group (which basically = the unique
identifier)

**Comment by AmineI** [comment]
Just noticed my comment didn't really make sense, It's a bit late here so forgive me about that - I meant  manually *updating a toast's text - I could parse the previous toast in my script using its known id, and recreate it with an additional info in the text for example, which could be a manual solution to #54

**Comment by Windos** [comment]
Ooh, I should probably update that ticket. There'll be a *much* better way
to update toasts in 0.7.0

**Comment by AmineI** [comment]
Any way to get the binded text :/ ? 
![image](https://user-images.githubusercontent.com/15179425/56218797-d9969a80-6065-11e9-883f-33c417f87517.png)

(The use case is that I'm looking to update a previously built toast by *appending* information to it, instead of replacing it)

**Comment by Windos** [comment]
Absolutely, one of the properties surfaced with `Get-BTHistory` includes the notification data, that stores that binding values:

![image](https://user-images.githubusercontent.com/6955786/56241904-2a040b80-60eb-11e9-911e-8166c0e7d0d2.png)

You'd need to pull these out and use them to build up a new hashtable for the update, but it'll let you know what was originally there.

**Comment by AmineI** [comment]
Ah, thanks ! I was actually looking in `Content` instead of `Data`, and couldn't figure out what was wrong.

**Comment by Windos** [comment]
Yeah, unfortunately that content isn't the "compiled" end result (something I didn't realise I wish was a thing until now)... it'll include placeholders for the bindings in curly braces (e.g. "{FirstLine}") but it's up to the Windows API to smush that and the NotificationData together when displaying the notification.
