### ISSUE TITLE
ShoulderTap Not Working (Win10 Ent 1803 and 1809)

### ISSUE THREAD

**Issue by Chirishman** [Windos/BurntToast#66]
Not sure if I've got some weird edge case thing going here but here's what I know might be different from typical testing scenarios

## Environment

- Win10 Ent
    - First tried under 1803, then updated to 1809, no change.
- Multiple in-place major version upgrades (not a clean install)
- O365/ADFS integrations
- Skype for Business present
- Windows Store Disabled by GP
- Mail app not configured

## Steps Tried

- New-BTAppId - as per blog post
    ```PowerShell
    New-BTAppId -AppId 'Microsoft.People_8wekyb3d8bbwe!x4c7a3b7dy2188y46d4ya362y19ac5a5805e5x'
    ```
- Check ShoulderTap regkey value is set to 'on' (1)
    ```PowerShell
    (Get-ItemProperty -Path 
    hkcu:\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\Advanced\People\ShoulderTap -Name ShoulderTap).ShoulderTap -eq 1
    ```
- Turn shoulder tap off by setting value to zero, reboot, turn it back on, reboot, try again
- Try using a locally saved copy of the gif instead of the imgur link from the blog post

No dice on anything so far, not sure what I'm doing wrong.

**Comment by Windos** [comment]
Heya, are you able to send through a screenshot of your desktop, the
contact's entry in the people app and the code you're running?

Cheers!

**Comment by Chirishman** [comment]
Yep, here:

![image](https://user-images.githubusercontent.com/7658840/55519947-0602ed80-5648-11e9-9da8-2bcda20294a5.png)

I've blurred out my username in the prompt and my company's name and logo in the email address and people thumbnail

![image](https://user-images.githubusercontent.com/7658840/55520031-685bee00-5648-11e9-835d-8114baaadcd7.png)

I get that it's slightly less helpful with that blurred out but I also have tried replacing the email address both in the contact and in the script with your provided example of stormy@example.com with no dice. Should have mentioned that in my initial post.

**Comment by Windos** [comment]
Hmm, can you do me a favour and put the email under "personal email"? I'm not in a position to check if it sees the different email fields differently at the moment... but it's a hunch lol.

![2019-04-04](https://user-images.githubusercontent.com/6955786/55520770-3b581b80-56da-11e9-94ea-175c17d4552b.png)

**Comment by Chirishman** [comment]
I've tried that too, and I just did it again, no dice. I'm wondering if the disabled windows store has something to do with this, maybe I've got some kind of old, non-current version of the People app...

**Comment by Windos** [comment]
That's very possible... is it possible to pull the version of the AppX
package?

**Comment by Chirishman** [comment]
Hm...

```PowerShell
Username ►► Get-AppxPackage -Name microsoft.People


Name              : Microsoft.People
Publisher         : CN=Microsoft Corporation, O=Microsoft Corporation, L=Redmond, S=Washington, C=US
Architecture      : X64
ResourceId        :
Version           : 10.1902.633.0
PackageFullName   : Microsoft.People_10.1902.633.0_x64__8wekyb3d8bbwe
InstallLocation   : C:\Program Files\WindowsApps\Microsoft.People_10.1902.633.0_x64__8wekyb3d8bbwe
IsFramework       : False
PackageFamilyName : Microsoft.People_8wekyb3d8bbwe
PublisherId       : 8wekyb3d8bbwe
IsResourcePackage : False
IsBundle          : False
IsDevelopmentMode : False
NonRemovable      : False
Dependencies      : {Microsoft.NET.Native.Framework.2.2_2.2.27405.0_x64__8wekyb3d8bbwe,
                    Microsoft.NET.Native.Runtime.2.2_2.2.27328.0_x64__8wekyb3d8bbwe,
                    Microsoft.VCLibs.140.00_14.0.27323.0_x64__8wekyb3d8bbwe,
                    Microsoft.People_10.1902.633.0_neutral_split.scale-150_8wekyb3d8bbwe...}
IsPartiallyStaged : False
SignatureKind     : Store
Status            : Ok
```

**Comment by Windos** [comment]
Hmm, that's actually a newer version than I have installed...

I'll do some more digging.

**Comment by Chirishman** [comment]
So on my personal machine (Win10 Pro 1809) it works. Package version there is **10.1812.10232.0**

Mail app is configured (sort of) and none of the other BS applies. Exact same command was used except for a different email address.

Just some additional data points.

**Comment by Chirishman** [comment]
It also works on a different domain joined  Win10 Ent 1809 computer than I was trying this on yesterday, which happens to be running **10.1812.10232.0**

Maybe **10.1902.633.0** is the problem...

**Comment by Windos** [comment]
That machine with 10.1902 isn't running an insider build by chance?

**Comment by Chirishman** [comment]
Nope, bone stock. My current hypothesis is that 10.1902 got released, but then was unpublished and this machine happened to suck down 10.1902 when it was created before the Store app got disabled and because the Store app was disabled it never got the subsequent rollback command.

The windows store is currently serving 10.1812.10232.0 so I'm going to try sideloading that version onto the effected computer.

**Comment by Chirishman** [comment]
Sideloading hasn't fixed it. I'm at a loss.

Since I can't reproduce it on another machine right now, even a VM built from the same source image with the same RSOP I think that you can go ahead and close this for now. We can reopen it if I or someone else manages to reproduce the problem.

**Comment by PlasmatikSteak** [comment]
I'm experiencing this problem on my domain-joined pc.

Microsoft.People version = 10.1909.2812.0

Tried adding contact to Persons with the email I call New-BurntToastShoulderTap with.

I always just returns the fallback toast.

Also tried all the things in op's post.

**Comment by Windos** [comment]
Unfortunately, Shoulder Taps ended up being way too much work to setup, and once setup way too flaky to be relied upon.

Starting in v0.8.1 there will be a deprecation notice when using the related cmdlets:

![obsolete function notice](https://user-images.githubusercontent.com/6955786/93180034-a8565880-f78a-11ea-849e-48a1a9102130.png)

And those cmdlets will not ship with v0.9.0.
