### ISSUE TITLE
Notification icon seems to be dark

### ISSUE THREAD

**Issue by jwood79** [Windos/BurntToast#67]
Not sure how to correct this one. When I try to create just a default toast to say 'hi' for example,  it shows in the notification area very dark.

![notification](https://user-images.githubusercontent.com/48693373/56239492-275bd480-605f-11e9-9756-066061d110b6.JPG)

**Comment by jwood79** [comment]
This is just after installing the module on a new PC.

**Comment by Windos** [comment]
The short answer is that it's all about the [AppId](https://toastit.dev/2018/02/04/burnttoast-appid-installer/).

There's two possibilities for it being grey now and not on the old PC:

- What was the Windows 10 version on the old machine?
- What was the AppId set to? (Is it possible you'd installed the msi mentioned in the linked blog post and started using that?)

If the answer to those questions don't jump out at me as the reason, then I might start asking for some registry info if that's alright.
