### ISSUE TITLE
UTF-8 or Windows-1250

### ISSUE THREAD

**Issue by Azarchaniel** [Windos/BurntToast#68]
Hey, is there a way how to create Toast in UTF-8 or Windows-1250 (or similar)? I'm writing in my mother language (Slovak), we have special characters and BurntToast doesn't show it correctly. Any ideas?

**Comment by Windos** [comment]
Hey @Azarchaniel, does GitHub display the characters properly? If you wouldn't mind, could you reply with a sample of what you'd like to see work and I'll see what I can do!

**Comment by Azarchaniel** [comment]
Hey, I'm currently running Ubuntu, therefore I can't check it now. But I have noticed, that after some time, it started to work properly, with regional characters showed as they should be. Cannot tell you, if it was by my action or developers changed something. You can check my code [here](https://github.com/Azarchaniel/DBKLP/blob/master/dbklp.ps1), it's the same code as I was running including messages in special characters.
