### ISSUE TITLE
BurntToast Install

### ISSUE THREAD

**Issue by Eperrial** [Windos/BurntToast#73]
hi, i take BurntToast.zip and i unzip this file in C:\Users\Moi\Documents\WindowsPowerShell\modules\
when i make "Import-Module" on my Powerhsell termincal, i have multiple error like this... 

![image](https://user-images.githubusercontent.com/38047623/61938886-64a2fd00-af92-11e9-91ff-ced83db2b4f3.png)

**Comment by Windos** [comment]
Hey @Eperrial, chances are that Windows has blocked the files (especially the .dll) as it was downloaded from the internet.

Before unzipping, right click on the zip file and go into the properties,  tick "unblock files", and choose apply. You can then unzip the archive and it should work. You can also unblock the files using the [Unblock-File](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.utility/unblock-file?view=powershell-6) cmdlet.

Alternativly, you can have a trouble free install by getting it from the PowerShell Gallery: `Install-Module -Name BurntToast -Scope CurrentUser`

**Comment by Eperrial** [comment]
I'm pretty sure I did, and I'll try again and see if it fixes.

Before, I tried to Install with the PowerShell Gallery, but I can't continue installation because it needs to install NuGet before.
But I my computer I have VSCode and it's work, but on the other computer when VSCode is missing, this isn't works

**Comment by Eperrial** [comment]
It's works ;) Thanks !
