### ISSUE TITLE
Custom Audio Not Working

### ISSUE THREAD

**Issue by brendantop** [Windos/BurntToast#74]
I have been successful in using all of the built-in windows options via "New-BTAudio -Source" but no custom audio is working using "New-BTAudio -Path". I have tried mp3 and wav files. I don't get an error of any sort, the notification simply appears but the default notification sound is played instead of the custome file specified.

**Comment by Windos** [comment]
I'm seeing this as well, thinking this could be a change in the Windows API in an update at some point online the line.

To help with the troublshooting, can you let me know your Windows version and the output of `$PSVersionTable`?

**Comment by brendantop** [comment]
Windows 1809 (We also have machines on 1607, 1903). All the testing I've done is from my machine to others. I'll try some others.

Name                           Value
----                           -----
PSVersion                      5.1.17763.134
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.17763.134
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

**Comment by Windos** [comment]
I spun up an 1803 VM and the audio is working there, I'll have to find out what's changed between 1803 and 1809.

**Comment by Windos** [comment]
It looks like it's a known issue that's very low down the priority list to fix (if it's even on the list to fix): https://github.com/MicrosoftDocs/windows-uwp/issues/1593

**Comment by brendantop** [comment]
Darn, I take it Desktop Bridge is not an option?

**Comment by Windos** [comment]
I'm going to keep an eye on this, but unfortunately it looks like custom sounds might be on the outs.
