### ISSUE TITLE
New-BTButton question

### ISSUE THREAD

**Issue by jwood79** [Windos/BurntToast#75]
Is there a way to display a button to just dismiss the notification that pops up? I have a script that checks for pending reboots on a PC and shows a notification if there is one. I want a dismiss button to display so they can dismiss it.

I can get a snooze and dismiss button, but I just want a dismiss button.

Thanks in advance.

**Comment by Windos** [comment]
Absolutely, use `New-BTButton` to create the button and specify the `-Dismiss` switch:

```powershell
New-BurntToastNotification -Button (New-BTButton -Dismiss)
```

![Toast with Dismiss](https://user-images.githubusercontent.com/6955786/65278011-54b52d00-db7f-11e9-93d4-ba6f7b17f886.png)

_Note that clicking on the toast body (not the small cross or arrow up the top right) also dismisses the toast, but that's nowhere near as discoverable for a user as a clearly labeled button._
