### ISSUE TITLE
Documentation on HTTP Listener

### ISSUE THREAD

**Issue by pfurches** [Windos/BurntToast#76]
Apologies is this is in the wrong place or I missed the documentation somewhere else but I ahve looked far and wide and do not see this.

Is there any documentation on the http listener functionality?

In our case, we would like to be able to send toast notifications to our domain clients and have them listen for these toast notifications from our network team about outages or upcoming events? But I cannot find anything that helps me set this up.

TIA for any help you can provide.

**Comment by Windos** [comment]
This isn't a feature of BurntToast itself, just an interesting example usage that @Cirzen provided that uses a .NET HTTP listener. The example itself is here:

[Example08](https://github.com/Windos/BurntToast/blob/master/Examples/Example08/Example08_Default.ps1)

If you wanted to do this across your entire network using the same method as the example, you'd need to start the PowerShell job containing the listener on ever individual workstation, and then when you wanted to trigger the Toast you'd have to fire off a POST request to every individual workstation. All of the workstations would need to have the BurntToast module installed.

A better method might be to just do this with a scheduled task in a GPO. You can even avoid the need to install the module on all of the workstations by [extracting the XML](https://toastit.dev/2018/08/21/crouton-8-i-like-your-code-but-i-dont-want-it-on-all-my-computers/).

At a high level that would be: extract the XML and put it in a common location. Have a scheduled task (set to go out when the message needs to go out) that loads that XML and use it to display a toast.

That obviously only really works if you've got a fair amount of notice, as it would take time for the clients to pick up the change in a GPO.
