### ISSUE TITLE
Comment based help spring clean

### ISSUE THREAD

**Issue by Windos** [Windos/BurntToast#77]
The documentation on many functions in this module, especially around the examples, is lacking.

If you've got the documentation bug, please help!

**Comment by tomlarse** [comment]
Have you considered converting the documentation to markdown using [PlatyPS](https://github.com/PowerShell/platyPS)? It would give you web documentation in addition to Get-Help documentation.

I generated a quick example here:
https://github.com/tomlarse/BurntToast/blob/iss77/docs/

And the externalhelp MAML-XML file here:
https://github.com/tomlarse/BurntToast/blob/iss77/BurntToast/en-US/BurntToast-help.xml

**Comment by Windos** [comment]
I did a long time ago (that's how the current [markdown help](https://github.com/Windos/BurntToast/tree/master/Help) was generated... but it's now well out of date.)

External and/or Update-able help has also been on my backlog for ages, but I can handle that once everything is up to date.

**Comment by 1RedOne** [comment]
I'll do a bit of this but I feel there is room for a couple folks to dig in. Many hands makes light work.

**Comment by Windos** [comment]
Absolutely! There's a **tonne** to be done and plenty of room for multiple PRs from people.
