### ISSUE TITLE
Error when doing import of module for 0.5 / 0.5.1

### ISSUE THREAD

**Issue by KurtDeGreeff** [Windos/BurntToast#8]
Hi,
Got following error
Failed to import function C:\Program Files\WindowsPowerShell\Modules\BurntToast\0.5.0\Public\Advanced\New-BTAction.ps1: Multiple ambiguous overloads found for ".ctor" and the argume
nt count: "1". (raised by: Write-Error)
Failed to import function C:\Program Files\WindowsPowerShell\Modules\BurntToast\0.5.0\Public\Advanced\New-BTAudio.ps1: Multiple ambiguous overloads found for ".ctor" and the argumen
t count: "1". (raised by: Write-Error)
Failed to import function C:\Program Files\WindowsPowerShell\Modules\BurntToast\0.5.0\Public\Advanced\New-BTBinding.ps1: Multiple ambiguous overloads found for ".ctor" and the argum
ent count: "1". (raised by: Write-Error)
Failed to import function C:\Program Files\WindowsPowerShell\Modules\BurntToast\0.5.0\Public\Advanced\New-BTButton.ps1: Multiple ambiguous overloads found for ".ctor" and the argume
nt count: "1". (raised by: Write-Error)
Failed to import function C:\Program Files\WindowsPowerShell\Modules\BurntToast\0.5.0\Public\Advanced\New-BTContent.ps1: Multiple ambiguous overloads found for ".ctor" and the argum
ent count: "1". (raised by: Write-Error)
Failed to import function C:\Program Files\WindowsPowerShell\Modules\BurntToast\0.5.0\Public\Advanced\New-BTContextMenuItem.ps1: Multiple ambiguous overloads found for ".ctor" and t
he argument count: "1". (raised by: Write-Error)
Failed to import function C:\Program Files\WindowsPowerShell\Modules\BurntToast\0.5.0\Public\Advanced\New-BTImage.ps1: Multiple ambiguous overloads found for ".ctor" and the argumen
t count: "1". (raised by: Write-Error)
Failed to import function C:\Program Files\WindowsPowerShell\Modules\BurntToast\0.5.0\Public\Advanced\New-BTInput.ps1: Multiple ambiguous overloads found for ".ctor" and the argumen
t count: "1". (raised by: Write-Error)
Failed to import function C:\Program Files\WindowsPowerShell\Modules\BurntToast\0.5.0\Public\Advanced\New-BTSelectionBoxItem.ps1: Multiple ambiguous overloads found for ".ctor" and 
the argument count: "1". (raised by: Write-Error)
Failed to import function C:\Program Files\WindowsPowerShell\Modules\BurntToast\0.5.0\Public\Advanced\New-BTText.ps1: Multiple ambiguous overloads found for ".ctor" and the argument
 count: "1". (raised by: Write-Error)
Failed to import function C:\Program Files\WindowsPowerShell\Modules\BurntToast\0.5.0\Public\Advanced\New-BTVisual.ps1: Multiple ambiguous overloads found for ".ctor" and the argume
nt count: "1". (raised by: Write-Error)
Failed to import function C:\Program Files\WindowsPowerShell\Modules\BurntToast\0.5.0\Public\Advanced\Submit-BTNotification.ps1: Multiple ambiguous overloads found for ".ctor" and t
he argument count: "1". (raised by: Write-Error)

**Comment by Windos** [comment]
Thanks for the report!

To help track it down, would you mind letting me know which OS version you're running and the output of $PSVersionTable ?

**Comment by KurtDeGreeff** [comment]
Thanks, here you go: 
Windows 7 Enterprise SP1 with following PS version
Name                           Value                                                
----                           -----                                                
PSVersion                      5.0.10586.117                                        
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0, 5.0.10586.117}                  
BuildVersion                   10.0.10586.117                                       
CLRVersion                     4.0.30319.42000                                      
WSManStackVersion              3.0                                                  
PSRemotingProtocolVersion      2.3                                                  
SerializationVersion           1.1.0.1

**Comment by Windos** [comment]
Ahh, my apologies Kurt. This will only work on Windows 8 or Windows 10 as the sub systems for Toast Notifications were only added in those versions.

I'm actually not sure if the current version works on Windows 8 either, as I've started using 'Adaptive' Toasts which, to my understanding, is Windows 10 only.

I can guarantee than [v0.4.0](https://github.com/Windos/BurntToast/releases/tag/v0.4.0) does work on Windows 8 (as that's what I was developing and testing on at the time.)

I'm currently downloading a Windows 8 ISO to see if the the current version on it and will work out a mechanism to stop the module from trying to load on anything that isn't supported.
