### ISSUE TITLE
Help with troubleshooting why notifications are not showing

### ISSUE THREAD

**Issue by ohk2kt3t4** [Windos/BurntToast#82]
Environment:
- Win10 Pro ver 1903 Build 18362.418
- Powershell v5.1 (also tested with Powershell Core v6.2)

Steps to reproduce:
```
Install-Module -Name BurntToast -Scope CurrentUser
New-BurntToastNotification  # There is no output in shell or on desktop from this cmd.
```

"what-if" output'

`What if: Performing the operation "New-BurntToastNotification" on target "submitting: <?xml version="1.0" encoding="utf-8"?><toast><visual><binding template="ToastGeneric"><text>{Default Notification}</text><image src="C:\Users\me\Documents\WindowsPowerShell\Modules\BurntToast\0.7.0\Images\BurntToast.png" placement="appLogoOverride" hint-crop="circle" /></binding></visual></toast>".`

```Get-StartApps | where AppID -eq '{1AC14E77-02E7-4E5D-B744-2EB1AE5198B7}\WindowsPowerShell\v1.0\powershell.exe'``` returns:
```
Name               AppID
----               -----
Windows PowerShell {1AC14E77-02E7-4E5D-B744-2EB1AE5198B7}\WindowsPowerShell\v1.0\powershell.exe
```
 
Anything else I can try to see what is going on? Is there a debug flag?

**Comment by Windos** [comment]
Couple of things to check.

What is the AppId set to in your `config.json` file? (It should default to `{1AC14E77-02E7-4E5D-B744-2EB1AE5198B7}\\WindowsPowerShell\\v1.0\\powershell.exe`)

Is focus assist turned on? It'll show a moon on the action center icon if it is, and this will suppress the notifications (they should still show in the action center though)

![focus assist](https://user-images.githubusercontent.com/6955786/68736415-7b568800-0645-11ea-9067-b57a291eb17d.png)

Is Windows set to show notifications for PowerShell (or apps in general)? Head into the **Settings** app, choose **System**, then **Notifications & actions**.

Make sure the general "Notifications" toggle is on:

![Notifications settings toggle](https://user-images.githubusercontent.com/6955786/68736646-14859e80-0646-11ea-81fb-e112a03b7438.png)

Scroll down and find Windows PowerShell, ensure it is toggled on:

![Windows PowerShell toggle](https://user-images.githubusercontent.com/6955786/68736671-2ff0a980-0646-11ea-9a0b-958ee28d285c.png)

Click Windows PowerShell to get to the advanced options for it. Make sure **Show notification banners** and **Show notifications in action center** are both ticked. I also like to bump the priority up to **Top**.

![Advanced settings](https://user-images.githubusercontent.com/6955786/68736771-780fcc00-0646-11ea-9170-9b7cd5dbe248.png)

**Comment by ohk2kt3t4** [comment]
> Is Windows set to show notifications for PowerShell (or apps in general)? Head into the Settings app, choose System, then Notifications & actions.

That was it. Cheers!
