### ISSUE TITLE
I'm still getting curly brackets, even with a default New-BurntToastNotification

### ISSUE THREAD

**Issue by Syrah-NL** [Windos/BurntToast#87]
Even without any parameter, the notification title still has { } around it.

**Comment by Windos** [comment]
The example from #52 is working ok for me...

What version of Windows 10 are you on and can you confirm which version of BurntToast you've got imported?

Cheers!

**Comment by Syrah-NL** [comment]
I'm on a Virtual Windows server from Strato, it says the version is Windows V20-49 (1810.12nl)
Hope that's enough, otherwise please let me know where I can find the version number you need. 

BurntToast version 0.7.0

**Comment by Syrah-NL** [comment]
Any chance you could make a fix for Windows Server 2016 (which looks exactly like Windows 10)? Would be great =) I'm using your tool to show all kinds of checks on my server status and website statuses in the action centre, it's really cool!

**Comment by KrX3D** [comment]
hi,

i have got the same problem on my Windows Server 2016 (version 1607)

**Comment by Windos** [comment]
I'll be tracking this issue via #81
