### ISSUE TITLE
Module crashing on Windows 10 machine

### ISSUE THREAD

**Issue by kivle** [Windos/BurntToast#9]
Hi,

I get the following exception when trying to use the New-BurnttoastNotification cmdlet:

```
Multiple ambiguous overloads found for ".ctor" and the argument count: "1".
At C:\Program Files\WindowsPowerShell\Modules\BurntToast\0.5.0\Public\Advanced\Submit-BTNotification.ps1:29 char:5
+     [OutputType($null)]
+     ~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodException
    + FullyQualifiedErrorId : MethodCountCouldNotFindBest
```

The issue seems to be [OutputType($null)]. I commented the line out manually in my local installation, and then the module seems to work without any issues. Maybe Microsoft have added some overloaded constructors for the OutputType attribute in newer versions of their frameworks, which means that Powershell can no longer resolve a constructor for $null.

Edit: It seems that this issue is reocurring across multiple other cmdlets in the module.

**Comment by Windos** [comment]
Thanks for the heads up. I was having an internal battle about whether I should strongly type the OutputType or not... and it appears the answer is no.

Just in case it helps, would you mind letting me know the output of `$PSVersionTable` ?

Thanks again,
Josh

**Comment by Windos** [comment]
Have just pushed a commit that removes all instances of this $null output specification. Should resolve the issue.

Thanks again for letting me know.
